### ISSUE TITLE
This works on KDE

### ISSUE THREAD

**Issue by tsoernes** [benzea/gnome-screencast#101]
Just thought I'd share that this also works on Fedora 30 KDE with X11, though the display 
does not appear in the Displays menu.

**Comment by benzea** [comment]
Sure, but very limited only. Unless they are implementing the XDG desktop portal for screensharing, which I doubt is the case currently.

i.e. X11 fallback, which will not work on wayland and only works if you have a single display.

**Comment by paultelles** [comment]
X11 on Ubuntu 19.10 with dual displays worked long enough to snap this photo :)

The laptop 1080p display is on the left and the external 4K display is on the right.

<a href="https://lh3.googleusercontent.com/YUVYEl3jaxi9nJcfAYVd-t7aHrOxqrDysbiYtyB1UbUBDTEOr_tp5Wzx-fi1FRu2Ne4OzJODGTo_7_Zc=w4028-h1830" onclick="window.open('https://lh3.googleusercontent.com/YUVYEl3jaxi9nJcfAYVd-t7aHrOxqrDysbiYtyB1UbUBDTEOr_tp5Wzx-fi1FRu2Ne4OzJODGTo_7_Zc=w4028-h1830', '_self');">
https://lh3.googleusercontent.com/YUVYEl3jaxi9nJcfAYVd-t7aHrOxqrDysbiYtyB1UbUBDTEOr_tp5Wzx-fi1FRu2Ne4OzJODGTo_7_Zc=w4028-h1830</a>

**Comment by benzea** [comment]
Depends on what you consider "work" to mean ;-)

**Comment by Futureknows** [comment]
Could anyone clarify how much it works on X11 KDE? I can get it to connect to a Samsung TV but then disconnects within 30 a seconds. Is it worth debugging or pursuing or is KDE a no go?

**Comment by benzea** [comment]
A disconnect after 30s means the keepalive is not working.
