### ISSUE TITLE
Codecs Autoinstaller can't find packages in Software

### ISSUE THREAD

**Issue by 4g0tt3nSou1** [benzea/gnome-screencast#110]
GND sees my display, but when I connect it says I do not have an audio or video codec required, but offers to install them, but when I click one, and it goes to find it in Software, it doesn't find anything.

**Comment by 4g0tt3nSou1** [comment]
I've also tried manually installing FDKAAC, and x264enc; along with exporting those envvars for debugging, with no success

**Comment by benzea** [comment]
Well, if gnome-software does not find it, then it probably is something for you distribution to figure out. I can't help you with that part all I can do is make sure we request installation of the correct gstreamer element.

Sorry, I fear I cannot help you any further unfortunately.

> I've also tried manually installing FDKAAC, and x264enc; along with exporting those envvars for debugging, with no success

You need the corresponding gstreamer element for them, not just the libraries.

**Comment by 4g0tt3nSou1** [comment]
If I may, I am on Ubuntu 19.10, with gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly all installed, so I have the Libraries themselves, and their gstreamer element counterparts. 

By that said, correct me if I am wrong; but I should be good to go? So what's missing?

**Comment by paultelles** [comment]
As I recall, the app offering to install the codecs under Ubuntu 19.10 is symptomatic of not having the ubuntu-restricted-extras package installed.

I wrote a blog post outlining how to install GNOME Network Displays with Ubuntu 19.10. This only applies to X11 and not Wayland:
<a href="https://blog.paultelles.com/2020/03/how-to-install-gnome-network-displays.html" onclick="window.open('https://blog.paultelles.com/2020/03/how-to-install-gnome-network-displays.html', '_self');">
https://blog.paultelles.com/2020/03/how-to-install-gnome-network-displays.html</a>
