### ISSUE TITLE
LG not visibile as sink - Ubuntu 19.10

### ISSUE THREAD

**Issue by Giggus** [benzea/gnome-screencast#112]
Hi, 

I followed this guide (https://blog.paultelles.com/2020/03/how-to-install-gnome-network-displays.html) and the your readme readme to install everything on my Ubuntu 19.10 system. 

By running G_MESSAGES_DEBUG=all gnome-network-displays I get this:
`(gnome-network-displays:4468): GLib-GIO-DEBUG: 20:51:47.977: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
(gnome-network-displays:4468): Gtk-DEBUG: 20:51:48.057: Connecting to session manager
** (gnome-network-displays:4468): DEBUG: 20:51:48.130: WFDP2PRegistry: Found a new device, creating provider
** (gnome-network-displays:4468): DEBUG: 20:51:48.130: WfdP2PProvider: Discover is now set to 1
** (gnome-network-displays:4468): DEBUG: 20:51:48.131: NdScreencastPortal: Aquired Portal proxy
** (gnome-network-displays:4468): DEBUG: 20:51:48.131: task is: 0x558654b86180

** (gnome-network-displays:4468): WARNING **: 20:51:48.132: Error calling DBus method during Screencast portal initialization: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop

** (gnome-network-displays:4468): WARNING **: 20:51:48.132: Error initing screencast portal: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop

** (gnome-network-displays:4468): WARNING **: 20:51:48.132: Screencasting portal is unavailable! It is required to select the monitor to stream!

** (gnome-network-displays:4468): WARNING **: 20:51:48.132: Falling back to X11! You need to fix your setup to avoid issues (XDG Portals and/or mutter screencasting support)!
** (gnome-network-displays:4468): DEBUG: 20:51:48.132: WFDP2PRegistry: Got NMClient
** (gnome-network-displays:4468): DEBUG: 20:51:48.135: NdPulseaudio: Querying sink info by name
** (gnome-network-displays:4468): DEBUG: 20:51:48.135: NdPulseaudio: Error querying sink info
** (gnome-network-displays:4468): DEBUG: 20:51:48.135: NdPulseaudio: Got a sink info for the expected name
`
and it gets stuck there.

Unfortunately I see no sinks...
My TV has webOS 4.7.1

What am I missing?

Thanks for your help

**Comment by paultelles** [comment]
Does your network driver support Wi-Fi Direct/P2P?

Check with iw phy0 info. Under supported interface modes, you should see P2P-client, P2P-GO, and P2P-device.

**Comment by benzea** [comment]
There is a `WfdP2PProvider` so yeah, NetworkManager has a device …

README has some details, but I think you are in the "uhoh, something weird is going on" situation where debugging gets harder and the README stops being helpful.

**Comment by Giggus** [comment]
> Does your network driver support Wi-Fi Direct/P2P?
> 
> Check with iw phy0 info. Under supported interface modes, you should see P2P-client, P2P-GO, and P2P-device.

Yes it does as benzea says.
So what can I do? Any suggestions? :)

**Comment by benzea** [comment]
Well, the question is what is happening …

Basically, to debug this you'll need to sniff the wifi probing. For example, helpful would be trying to monitor a successful connection establishment. But that isn't easy to pull off overall (correct channel, loads of other stuff, etc.). But, if one has that, one could check if there is something weird with the wifi frames.

Also, the README does suggest one gdbus command that you can try to set the WFDIEs earlier. That **might** help.
