### ISSUE TITLE
Can not find Microsoft display adapter v1

### ISSUE THREAD

**Issue by kostadinstoilov** [benzea/gnome-screencast#114]
I am running fedora 31, gnome on wayland.
version: gnome-network-displays-0.90.2-2.fc31.src.rpm

My miracast adapter is the Microsoft display adapter v1 and I can not find it in gnome network displays. Note the sink found in the log is probably my neighbour's laptop.

It seems like my wi-fi adapter does not support monitor mode so I cannot do:
```iw phy phy0 interface add mon0 type monitor```

Attaching output of
```iw phy phy0 info```
and
```G_MESSAGES_DEBUG=all gnome-network-displays```

[gnome-network-displays.txt](https://github.com/benzea/gnome-network-displays/files/4536084/gnome-network-displays.txt)
[iw-info.txt](https://github.com/benzea/gnome-network-displays/files/4536086/iw-info.txt)

**Comment by benzea** [comment]
You neighbours laptop is a sink? Now that seems odd … I mean, I would expect it to be a peer, but not a sink …

```
** (gnome-network-displays:10610): DEBUG: 20:45:27.918: WFDP2PProvider: Found a new sink with peer 0x7f7d08005930 on device 0x55eee109c310
```

I should have added the MAC and other information about the found sink into the log (I probably improved that part but didn't upload new packages to fedora yet) … but, are you sure that is not the MS device?

**Comment by kostadinstoilov** [comment]
Hi, thanks for reaching out.
I am sure it's not the MS device. Name is something like 'XLaptop' and I only see it in particular parts of the house, it comes and goes.
Let me know if there is anything I can do for debugging.
