### ISSUE TITLE
Virtual Screens?

### ISSUE THREAD

**Issue by NaheemSays** [benzea/gnome-screencast#12]
It would be interesting to have the option to instead of casting the contents of the existing screen, to create a new virtual screen to be casted.

This would be useful for presentations and also cases where people have niche screen sizes, like ultrawidescreen monitors.

**Comment by benzea** [comment]
Yeah, this will require support in mutter though. I created an issue for that now, see https://gitlab.gnome.org/GNOME/mutter/issues/471

**Comment by mckarthik7** [comment]
I was able to do this in Xorg and intel GPU by adding virtual screens. Following this [stackexchange answer](https://unix.stackexchange.com/questions/378373/add-virtual-output-to-xorg), I was able to add virtual screeens to `xrandr` outputs.
After that, you add a mode by running -
`xrandr --addmode VIRTUAL1 1920x1080`
Replace VIRTUAL1 by whatever name you have for the virtual screen and the resolution as you need.
Then running 
`xrandr --output VIRTUAL1 --mode 1920x1080` 
should add the display. You should now be able to see it in settings under the name "unknown display" and shift its orientation as well.
It should also show up in gnome-network-displays as an option if you were able to set up the mutter screencast portal.

I was able to confirm this works on intel GPU driver. I had trouble adding virtual screens on Nvidia GPU though.

**Comment by edurenye** [comment]
This would be nice, we could select to mirror just one screen in a multi-screen setup.

Now I have to disconnect the external screen cast and connect the external screen again, in order to just cast the laptop screen.
