### ISSUE TITLE
Black screen with error "no session"

### ISSUE THREAD

**Issue by b1oki** [benzea/gnome-screencast#122]
From comment _https://github.com/benzea/gnome-network-displays/issues/105#issuecomment-626579914_

### Error description from comments

MiraScreen dongle writes "Do RTSP connection", than black screen. After about one minute disconnect.

**gnome-network-displays** window message "starting streaming": ![image](https://user-images.githubusercontent.com/1561897/81590607-7bf19080-93d4-11ea-941d-d9946a1f5866.png)

Last output from **gnome-network-displays** debug:
```
0:00:45.110326545 162143 0x560571fd0b00 INFO         GST_REFCOUNTING gstelement.c:3333:gst_element_finalize:<wfd-encoder-bin> 0x5605721ac930 finalize parent
0:00:45.110356366 162143 0x560571fd0b00 ERROR             rtspclient rtsp-client.c:2692:handle_setup_request: client 0x560571f8f420: media '/wfd1.0/streamid=0' not found
0:00:45.279725247 162143 0x560571fd0b00 INFO              rtspclient rtsp-client.c:3533:handle_request: client 0x560571f8f420: received a request PLAY rtsp://10.42.0.1:7236/wfd1.0/streamid=0 1.0
0:00:45.279773016 162143 0x560571fd0b00 ERROR             rtspclient rtsp-client.c:1870:handle_play_request: client 0x560571f8f420: no session
```

Wireshark capture screenshot: ![image](https://user-images.githubusercontent.com/1561897/81590408-30d77d80-93d4-11ea-9a93-ee6f5357e0af.png)

File from Wireshark: [miracast_no_session.pcapng.gz](https://github.com/benzea/gnome-network-displays/files/4611662/miracast_no_session.pcapng.gz)

#### wifi adapter
```
description: Wireless interface
product: AR9285 Wireless Network Adapter (PCI-Express)
vendor: Qualcomm Atheros
physical id: 0
bus info: pci@0000:02:00.0
logical name: wlp2s0
version: 01
width: 64 bits
clock: 33MHz
capabilities: bus_master cap_list ethernet physical wireless
configuration: broadcast=yes driver=ath9k driverversion=5.6.11-050611-generic firmware=N/A ip=192.168.43.92 latency=0 link=yes multicast=yes wireless=IEEE 802.11
resources: irq:16 memory:f4000000-f400ffff
```

#### p2p interface
```
p2p-wlp2s0-13: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.42.0.1  netmask 255.255.255.0  broadcast 10.42.0.255
        inet6 fe80::122c:5200:a073:706  prefixlen 64  scopeid 0x20<link>
        ether 1a:f4:6a:15:dd:6f  txqueuelen 1000  (Ethernet)
        RX packets 68  bytes 12978 (12.9 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 134  bytes 28020 (28.0 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

### Answer
@benzea _https://github.com/benzea/gnome-network-displays/issues/105#issuecomment-626932335_

> The problem seems to be:
> ```
> 0:00:52.851053205 148156 0x7fa2a0062760 ERROR             rtspclient rtsp-client.c:2692:handle_setup_request: client 0x5580233e33f0: media '/wfd1.0/streamid=0' not found
> ```
> But I can't see why that would happen. Comparing with an example that works, the only difference seems to be that your client includes the port number, which seems sane.
> 
> Though … there is this thing message:
> ```
> 0:00:52.850991823 148156 0x7fa2a0062760 INFO         GST_REFCOUNTING gstelement.c:3333:gst_element_finalize:<wfd-encoder-bin> 0x5580235cb840 finalize parent
> ```
> 
> Which I find rather suspicious. So maybe something else goes wrong earlier an the media simply disappears. And then it is correct that GStreamer cannot find the media.

**Comment by b1oki** [comment]
My plan:
- [x] Attach debug output and wireshark capture file when "no session"
- [x] Attach debug output and wireshark capture file when successful streaming

**Comment by benzea** [comment]
I would like to see the full log using `G_MESSAGES_DEBUG=all` from the start. This still doesn't make any sense to me, and I feel like I might be missing some important piece in the puzzle.

It looks like the pipeline just falls apart directly after prerolling. But I have no idea why that might be happening.

**Comment by b1oki** [comment]
> I would like to see the full log using `G_MESSAGES_DEBUG=all` from the start. This still doesn't make any sense to me, and I feel like I might be missing some important piece in the puzz

[gnome-network-displays_failure.log.gz](https://github.com/benzea/gnome-network-displays/files/4671480/gnome-network-displays_failure.log.gz)

[gnome-network-displays_failure.pcapng.gz](https://github.com/benzea/gnome-network-displays/files/4671483/gnome-network-displays_failure.pcapng.gz)

[gnome-network-displays_success_0.log.gz](https://github.com/benzea/gnome-network-displays/files/4671482/gnome-network-displays_success_0.log.gz)

[gnome-network-displays_success.log.gz](https://github.com/benzea/gnome-network-displays/files/4671481/gnome-network-displays_success.log.gz)

[gnome-network-displays_success.pcap.gz](https://github.com/benzea/gnome-network-displays/files/4671484/gnome-network-displays_success.pcap.gz)
