### ISSUE TITLE
ND_SINK_STATE_ERROR

### ISSUE THREAD

**Issue by agtonybarletta** [benzea/gnome-screencast#123]
Hi, I am having problems connecting to Windows using miracast.

gnome-network-displays find the right device name (my windows notebook name) but after a minute trying to connect it simply say ERROR.

I don't think it is a network problem since it finds the correct device and I can ping it.
I am using debian:
```
OS: Debian GNU/Linux bullseye/sid x86_64 
Kernel: 4.19.0-8-amd64
CPU: Intel i7-3537U (4) @ 3.100GHz 
GPU: Intel 3rd Gen Core processor Graphics Contro 
GPU: NVIDIA GeForce GT 740M 
```
Here is the output of the command `gnome-network-displays`
[output](https://gist.github.com/agtonybarletta/2305e65ad8566bfe21b3bf6819e744bc)

I tried to run the test with the parameter `NETWORK_DISPLAYS_DUMMY=1` but vlc failed
```Created new TCP socket 33 for connection
[00007f1c68001130] live555 demux error: Failed to connect with rtsp://localhost:7236/wfd1.0
[00007f1c6800b010] main stream error: connection failed: Connection refused
[00007f1c6800b010] satip stream error: Failed to setup RTSP session
[00007f1c6800b010] main stream error: connection failed: Connection refused
```

However I tried to create an rtsp stream using vlc (I streamed an mp4 file) and I tried to connect using my debian pc (with localhost) and using windows (using my debian ip) and it worked. 
RTSP seems to work fine.

**Comment by benzea** [comment]
Hmm, the log suggests that we never get a TCP connection to the RTSP server. Then, a bit later we go into the error state, I suspect the device disconnects again from the P2P Group and then NetworkManager closes the connection after 5 seconds.

Hard to tell, I guess the interesting part may be why the other side never connects. Does it get a DHCP address, does it try to connect, is there some other error? Is there maybe a firewall?

The README has some hints on how you can capture a TCP dump of the P2P interface. That might give some hints as to what is going on.


Though, to be honest, VLC not even being able to connect is a bit suspicious. But I think there are sometimes weird things (if it e.g. disconnects and the server disappears), so I am wouldn't take that seriously unless you are really seeing this consistently.
