### ISSUE TITLE
Connection errors with MS Display Adapter v2

### ISSUE THREAD

**Issue by scorpion81** [benzea/gnome-screencast#124]
Hi,
I have trouble establishing a connection to my adapter. (I am running the latest iteration of linux Manjaro, 20.01, on an Acer Aspire A515-52.) 
According to the output of ```G_MESSAGES_ALL=debug gnome-network-displays``` it seems to be able to connect, but the connection is instantly closed again.
Output:
[gnome-network-debug.txt](https://github.com/benzea/gnome-network-displays/files/4671656/gnome-network-debug.txt)

I was further investigating this problem by also trying out miraclecast and connecting manually via wpa_supplicant. When NetworkManager is disabled and wpa-supplicant is being started manually (not as service, not from dbus etc) it seems to connect with the pbc auto method like this:

[wpa_log_without_nm.txt](https://github.com/benzea/gnome-network-displays/files/4671659/wpa_log_without_nm.txt) (this is from an interactive wpa_cli session).
But this "connection" also closes a few seconds later...  According to the output of the manually started wpa_supplicant (it ran in foreground in a terminal) there were EAP failures.
``` wlan0: CTRL-EVENT-EAP-FAILURE c6:9d:ed:f1:dd:d1```
[wpa_log.txt](https://github.com/benzea/gnome-network-displays/files/4671668/wpa_log.txt)

With NetworkManager i do not reach the ```AP-STA-CONNECTED c6:9d:ed:f1:dd:d1 p2p_dev_addr=c6:9d:ed:f1:dd:d1``` line, but get group formation errors instead.

See this: 
[wpa_log_with_nm.txt](https://github.com/benzea/gnome-network-displays/files/4671664/wpa_log_with_nm.txt)

Been tinkering with this for several days now. I would like to do this a bit more systematically... so... i see in different issue posts here certain wpa_supplicant and network manager logs... but sorry for the question. What are the exact commands to generate those logs, or where do i have too look for the log files etc ?

Further note, i was also trying to connect with a PIN (was able to show it on-screen with wpa_cli) like this : ```p2p_prov_disc c6:9d:ed:f1:dd:d1 display``` and using it via ```p2p_connect c6:9d:ed:f1:dd:d1 <pin> display``` , the PIN for WPS is also accepted but connection closes anyways shortly after that. Hmmm.... i wonder why EAP authentication is being used anyways for this adapter....

I appreciate any help for this :)

EDIT: Hmmm, I seem to have managed to get a connection now, but even with the dummy sink the streaming seems to have errors..  (black screen) 
[dummy_sink_debug.txt](https://github.com/benzea/gnome-network-displays/files/4671885/dummy_sink_debug.txt)

What i did to get an IP address  even(temporarily):
1.Since i messed too much around in my manjaro install, i reinstalled it quickly.
2.To disable the interface renaming wlan0 -> wlxxxxx and avoid mac address randomization i did... 
create (or modify) `/etc/systemd/network/99-default.link `with a text editor:

```
[Link]
NamePolicy=none #avoids renaming
MACAddressPolicy=none #avoids mac randomization
```
and reboot.
Then i re-installed gnome-network-displays.. 

pipewire complained in journalctl about permissions, so screensharing needs to be enabled...

(taken from https://forum.manjaro.org/t/gnome-screen-sharing-breaks-in-3-36/131586/11)
1.    Uninstall vino
2.   Verify that gnome-remote-desktop is installed
3.    Modify /etc/gdm/custom.conf and put WaylandEnable=true in the [daemon] section
 4.  Reboot
 5.   Enable screen sharing again.

I will now investigate why the streaming even with the dummy sink fails.

**Comment by scorpion81** [comment]
After looking a bit further, i found out that the same error messages occur in pipewire as mentioned here https://github.com/benzea/gnome-network-displays/issues/113#issuecomment-619438506 (proxy 3 not found, etc), even when using just the dummy sink.

**Comment by scorpion81** [comment]
Note: Better be careful with this adapter, since if you also use it under windows, it will not properly connect there anymore too ! I literally tried everything, from simple troubleshooting tips up to mac spoofing and trying to carefully change some registry entries, that thing just doesnt seem to pair with windows any more. I suspect they exchanged some secret key or pin and if you do a connection attempt in linux, the adapter *seems* to memorize another key with the same computer mac address and hence in windows it wont work any more ! (Blindly guessing here, since google doesnt help very much if you dont know what specific terms you need to search for). Under windows it also doesnt prompt for a PIN, so some pbc pairing seems to go on, or the pin is just exchanged differently (not displayed)

**Comment by benzea** [comment]
Hmm, is this the device in question:

  https://www.amazon.de/Microsoft-Wireless-Display-kabellosen-Bildschirm%C3%BCbertragung/dp/B01C9YTI9S/ref=sr_1_3?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=microsoft+wireless+adapter+v2&qid=1590499526&sr=8-3
