### ISSUE TITLE
Can't see my Sony TV which is Miracast enabled

### ISSUE THREAD

**Issue by whereistejas** [benzea/gnome-screencast#13]
I have installed "gnome-screencast" from your COPR repo

**Comment by benzea** [comment]
That could be WFD IEs related and may mean we need to set them in the find operation already.

Could you try whether it starts showing up after running the following command?

```
gdbus call --system --dest fi.w1.wpa_supplicant1 --object-path /fi/w1/wpa_supplicant1 --method org.freedesktop.DBus.Properties.Set fi.w1.wpa_supplicant1 WFDIEs "<@ay [0x00, 0x00, 0x06, 0x00, 0x90, 0x1c, 0x44, 0x00, 0xc8]>"
```

You will need to run the command as root (e.g. using `sudo`).

**Comment by pengyver** [comment]
Hi, same problem with my Sony TV. I have tested command above but no luck

**Comment by benzea** [comment]
Hm, I still don't have an idea of what might be going on. So lets try to rule out some possible but unlikely errors:

Have you confirmed that you can see the TV using e.g. an android Miracast phone application?
Could you paste the command line output of `nmcli dev`?

**Comment by benzea** [comment]
I'll close the bug for now. Please reopen if you can provide the information I asked for.
