### ISSUE TITLE
Gnome-screencast crash 

### ISSUE THREAD

**Issue by ghost** [benzea/gnome-screencast#14]
After connecting to the tv the application crash with the following messages:

```
** (gnome-screencast:3347): WARNING **: 10:11:11.347: WfdClient: No resolution found, falling back to standard FullHD resolution.

(gnome-screencast:3347): GStreamer-CRITICAL **: 10:11:11.421: gst_bin_add: assertion 'GST_IS_ELEMENT (element)' failed

(gnome-screencast:3347): GLib-GObject-CRITICAL **: 10:11:11.421: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(gnome-screencast:3347): GLib-GObject-CRITICAL **: 10:11:11.421: g_object_set_data: assertion 'G_IS_OBJECT (object)' failed

** (gnome-screencast:3347): ERROR **: 10:11:11.464: WfdMediaFactory: Error creating encoding pipeline. If gstreamer is compiled with debugging and GST_DEBUG_DUMP_DOT_DIR is set, then the pipeline will have been dumped.

```

**Comment by benzea** [comment]
Oh, nice ;-)

Could you try running with `GST_DEBUG_DUMP_DOT_DIR=/tmp gnome-screencast`. You should then get a file `/tmp/wfd-pipeline.dot` and attach it here. Also, could you run `gst-inspect-1.0` and attach the full output?

**Comment by benzea** [comment]
Oh, actually no need to provide that … the only possible explanation is that we fail to create the h264 encoder element.

My best explanation would be that you have none of the required codecs installed. Did you install this using the copr repository?

Probably I just need to add a dependency to the copr package so that the openh264 encoder is guaranteed to be there (it is the fallback encoder we use).

**Comment by benzea** [comment]
@mrepetto94 please install `gstreamer1-plugin-openh264`, that should fix it.

I'll close the bug once I have updated the copr repository to make the plugin a dependency.

**Comment by ghost** [comment]
I firstly used the copr but then because of the crashing I built it directly from the git repo. However, as you said was a problem of dependency. I installed gstreamer1-plugin-openh264 and now everything works perfectly :-)

**Comment by benzea** [comment]
About to do a new build, closing

**Comment by alanmilinovic** [comment]
How to install gstreamer1-plugin-openh264 on ubuntu?

**Comment by benzea** [comment]
Sorry, I really can't help you with that (maybe someone else can comment).

Though I think there should be a warning if openh264 cannot be found, simply erroring out earlier on.
