### ISSUE TITLE
How can we try this out? no Install guide

### ISSUE THREAD

**Issue by affansyed** [benzea/gnome-screencast#15]
How complete is this? are their instruction on how to try this out.?

**Comment by eduarmreyes** [comment]
@affansyed as far as I know, these are the steps to install it.

https://copr.fedorainfracloud.org/coprs/benzea/screencast/

**Comment by benzea** [comment]
@affansyed, is the copr repository good enough?

In general, to try it out you'll need a very recent NetworkManager and then compile it yourself (unless you can use the copr repository). The procedure for compiling/installing this module is very similar to other software, so I am not sure it makes sense to write detailed instructions. I think the better approach is to get it into shape enough that distributions can start shipping it.

**Comment by benzea** [comment]
Closing, a dedicated guide is currently out of scope. That might change though, but ideally the idea is still to integrate it more tightly into GNOME (e.g. having a link in the display panel to open this application).
