### ISSUE TITLE
Invalid unclassed Pointer 

### ISSUE THREAD

**Issue by Cellebyte** [benzea/gnome-screencast#17]
## Description

Build the project using

* meson: 0.49.2
* ninja: 1.9.0
* gnome: GNOME Shell 3.32.0
* xdg-desktop-portal: 1.2.0-2
* xdg-desktop-portal-gtk: 1.2.0-1
* libnm: 1.16.0-1
* x264
* faac
* os: ArchLinux

Builds like a charme.

## Error Message
I do not know which cast was meant but the application does not show up.

```bash
** (gnome-screencast:10589): WARNING **: 18:41:22.277: Error initing screencast portal: Failed to create portal sesssion

(gnome-screencast:10589): GLib-GObject-WARNING **: 18:41:22.280: invalid unclassed pointer in cast to 'GnomeScreencastWindow'
```

**Comment by benzea** [comment]
Sounds to me like you have the screencast portal, but you don't have support in mutter for screencasting or something like that.

Do you get a window to choose the screen you want to cast?

**Comment by Cellebyte** [comment]
@benzea
Thats the problem I get no window at all.
I am using Gnome and Wayland.

**Comment by benzea** [comment]
@Cellebyte, I believe the issue is that you compiled mutter without pipewire support (IIRC, enabling pipewire enables the screencasting support).

I added a workaround to also fall back to X11 in your case. This is *not* desirable though and you should fix your setup!

**Comment by Cellebyte** [comment]
Thanks for your hotfix. I will dig into it and will try to fix it. The problem was, that I am not really good at debugging C Code :) So now that I know my setup is the broken part in the chain I can try to fix that.
