### ISSUE TITLE
Chromecast support

### ISSUE THREAD

**Issue by benzea** [benzea/gnome-screencast#18]
It would be nice to support other devices and not only Miracast (revision 1).

One such device that a lot of users at home would likely benefit from is the Chromecast. An implementation is available in VLC.

In principle it looks like the following is needed:
 * [ ] Implement a stream that can be downloaded via HTTP from our machine (i.e. we need a simple "HTTP server" that is able to serve the stream as one large "file". We can probably use the same codecs as for WFD, but we'll need a different container.
 * [ ] Implement discovery of chromecasts (using avahi)
 * [ ] Implement the command and control required to start/stop/restart streaming on the chromecast

**Comment by obook** [comment]
For stream to a Chromecast, you can directly use Google Chrome.

**Comment by 1989gironimo** [comment]
Or use [this](https://github.com/Rafostar/gnome-shell-extension-cast-to-tv)
