### ISSUE TITLE
The patch does not apply

### ISSUE THREAD

**Issue by edurenye** [benzea/gnome-screencast#2]
The patch does not apply.
Is the patch needed? Why you did not create a pull request to the gst-rtsp-server repository like you did with NetworkManager?

**Comment by benzea** [comment]
Because it was never cleaned up.

I am actually moving over to use C, which will make most of the patch obsolete. The reset will obviously be upstreamed.

**Comment by benzea** [comment]
Alright, C version pushed. The patch is not needed anymore.

**Comment by benzea** [comment]
This version will actually stream the desktop. Not very well, but when it starts, the image does get through for me – updating is rather random for me though..

**Comment by edurenye** [comment]
Great! I'll try during the weekend

**Comment by edurenye** [comment]
I tried to install network-manager with your PR on Ubuntu 18.10.
First I purged network-manager.
I installed all dependencies, too many.
I did run meson, it worked.
But then I run ninja and I got an error saying:
`
qt/monitor-nm-running.cpp:89:10: fatal error: monitor-nm-running.moc: No such file or directory
`
I couln't find out what was wrong, so I coudn't test anything

**Comment by benzea** [comment]
Seems like a network manager build issue relating to the QT integration.

Maybe build with "-Dqt=false" (that is for meson). That disables the QT integration and probably works around that issue.

Note that I did an important bugfix in the patchset yesterday.

**Comment by edurenye** [comment]
It worked, I could compile NM, now I need to add it to the meson of gnome-screencast
I tried with `meson build -D libnm=~/NetworkManager-wip-P2P/build/libnm/libnm.so` but it did not work.
It cannot find libnm.
This did not work neither: `export PATH=$PATH:/home/eduard/NetworkManager-wip-P2P/build/libnm`

**Comment by benzea** [comment]
I could provide a copr repository which installs the test version of NetworkManager and also the lastest gnome-screencast. Do you think that would work for you?

**Comment by edurenye** [comment]
I use Ubuntu, but since what I want is to test it, I'll do it in a fedora VM, so yes, that could work.
And would make easy for others to also test it.

But I still wonder why my build didn't work.

Thanks for your help, and all the effort you put in your project! I'm willing to test it.

**Comment by benzea** [comment]
Hah, Ubuntu doesn't work currently as they disable pipewire support in mutter unfortunately (I have a compile time flag right now, but might actually do some fallback handling to X11 to not use the proper screencasting support in GNOME).

The build s working fine. You will need to actually install it into some location and then set the paths properly. One way you could do this is `jhbuild`.

VM may not work as this is wifi P2P stuff which needs direct access to the card :)

**Comment by edurenye** [comment]
I'll test it when I have time, for VM I'll use a USB wifi, so I can passthrough it to the VM, that should work.

**Comment by benzea** [comment]
Sorry, I ran into some issues with creating the NetworkManager packages and I gave up.

I'll write again when I have more news; other than that, things did start working quite nicely for me here after fixing some streaming and protocol errors.

**Comment by benzea** [comment]
OK, everything is build now: https://copr.fedorainfracloud.org/coprs/benzea/screencast/

Please note that it appears the NM packages were *not* signed. I am not sure why, but you may need to edit the repository file in `/etc/yum.repos.d` and set `gpgcheck=0`.

**Comment by benzea** [comment]
Heh, also, one currently needs to disable selinux policy enforcing (i.e. `setenforce 0`). See https://github.com/fedora-selinux/selinux-policy/issues/238
