### ISSUE TITLE
New name?

### ISSUE THREAD

**Issue by bertob** [benzea/gnome-screencast#22]
The current name is a bit confusing, as "screencast" is most commonly used for video recordings of the screen (analog to "screenshot"). 

Some clearer, but still generic alternatives (from the IRC discussion last week) if we intend this to be an "official" GNOME app:
- Network Displays
- Remote Displays
- Wifi Displays

On the other hand, if this is intended to be a third-party app we could brainstorm some less generic names.

**Comment by 4ndrej** [comment]
Wifi Display or Wireless Display

**Comment by benzea** [comment]
I think I personally favour "Network Displays". While the application is currently focused on "Wi-Fi Display" (i.e. Miracast), I believe that we would want to integrate similar technologies into the same application if/when we support them (e.g. Chromecast is probably quite common).

It would probably make sense to adjust the name of the binary too at the same time and the internal code prefixes (e.g. gnome-network-displays).

**Comment by NaheemSays** [comment]
I think a good replacement name will be DisplayCast.

It has the benefit of a unique name along with association with "cast" without associating with screencasting which is a commonly used term for screen recording.

If integrated into Gnome Settings then it wont need its own unique name, but at this stage it isnt and is a separate application
