### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by bertob** [benzea/gnome-screencast#23]
As discussed on IRC, here's the app icon I've been playing with:

![image](https://user-images.githubusercontent.com/1908896/55801005-5c06e380-5ad5-11e9-9149-0f740b333dfa.png)

This would work for all the generic new app names proposed in #22, but if the name ends up changing, I can try something else.

**Comment by benzea** [comment]
Great stuff. Would it be OK to use this icon already (right now I don't have any)? If yes, where could I grab it?

**Comment by bertob** [comment]
Here are the hicolor and symbolic in a zip (Github doesn't allow svg):

[org.gnome.NetworkDisplays.zip](https://github.com/benzea/gnome-screencast/files/3130446/org.gnome.NetworkDisplays.zip)
