### ISSUE TITLE
gnome-screencast howto?

### ISSUE THREAD

**Issue by joakim-tjernlund** [benzea/gnome-screencast#24]
I tried gnome-screencast under X11/MATE and I cannot see anything to cast to.
We have projectors here which Windows can cast too but I don't see any of them in
gnome-screencast.

Am I missing something?
I use Gentoo with a custom kernel, is there something I need to add?

**Comment by joakim-tjernlund** [comment]
Using Lenovo Thinkpad T480s with Intel Wifi

**Comment by joakim-tjernlund** [comment]
hmm, maybe wpa_supplicant p2p needs to be enabled too ... :)

**Comment by benzea** [comment]
Yes, P2P support in wpa supplicant would be a good idea :)

Did you solve your issue? I don't think a longer howto is in the scope for me to work on for now. If anyone wants to update the README or similar, then I would be happy to merge it though.
