### ISSUE TITLE
gnome-screencast does not see all WiFi Display devices. 

### ISSUE THREAD

**Issue by joakim-tjernlund** [benzea/gnome-screencast#27]
Trying out screencast  on our X11 laptops we can see neighbouring WiFi display devices
but our own projectors (Epson)  does not show up.
Is Epson different? Maybe something we have forgotten ?

**Comment by benzea** [comment]
I had multiple people saying that Epson (or was it Panasonic?) devices cannot be discovered, but you are the first who is able to specify that other devices work fine.

I think the ideal thing here would be a if you create a dump of the wifi frames. Maybe then it will become clear what is going on. This would work by running:
 * `iw phy phy0 interface add mon0 type monitor`
 * `ip link set mon0 up`
 * Create a dump for `mon0` in wireshark while gnome-screencast is running and searching for devices (or by running `tcpdump -i mon0 -w dump.pcap`
 * `iw dev mon0 del` to remove the device again

The above is the most interesting dump, but you can also:
 * Use [this script](https://benjamin.sipsolutions.net/dbus-dump.py) with `python2 ./dbus-dump.py org.freedesktop.NetworkManager fi.w1.wpa_supplicant1` (as root) to store all available information from NetworkManager and wpa_supplicant (I am only interested in the paths where the P2P peers would show up).
 * Run with `G_MESSAGES_DEBUG=all gnome-screencast`, which might give us some more information, but I am not too hopeful about that

**Comment by joakim-tjernlund** [comment]
[dump.zip](https://github.com/benzea/gnome-screencast/files/3148697/dump.zip)

Seems like get a null answer when we probe.
The name for Epson proj should be Triton

**Comment by benzea** [comment]
I am somewhat confused. I see 74:e5:f9:0a:cc:ed making probe requests, which look correct. But then, there are a lot of responses to b4:6b:fc:3e:b6:e8 for which I don't see corresponding probe requests.

So, my guess right now is that the first is the Linux machine, while the second some other machine that is also scanning (but we didn't see the probe requests).

This doesn't add up for me right now.

**Comment by joakim-tjernlund** [comment]
OK, lets see if I can get another dump with less interference.

**Comment by benzea** [comment]
Hm, it could be more useful to get a dump of another device finding it. i.e. you let monitoring running on a laptop next to a windows machine that can see the projector (please provide the MAC address of the windows machine then).

**Comment by benzea** [comment]
There is also Microsoft Message Analyzer. If you grab a trace of a working connection using that, that would probably be really useful. https://docs.microsoft.com/en-gb/message-analyzer/microsoft-message-analyzer-operating-guide

**Comment by joakim-tjernlund** [comment]
I figured we could use an parallel Linux box to do the dumping(using the mon0 setup) but that does not seem to work. The Microsoft Message Analyzer is yet another tool I not familiar with and I don't have a Windows box so I need help of 3:d party to do dumping.
Using Wireshark on Windows did not either work, can one setup a mon0 I/F on Windows too?

**Comment by benzea** [comment]
Unfortunately wireshark on windows is not able to capture the relevant information. I have tried, it cannot see the P2P interface, and I am guessing it also has trouble with the probe requests already.

**Comment by benzea** [comment]
A linux machine is able to see the frames. However, you might (even randomly) end up on a different channel, and then you simply will not see the relevant wifi frames.

**Comment by joakim-tjernlund** [comment]
hmm, maybe we will have better luck if we disconnect our machines (both Linux and Windows) from our
WiFi Network before dumping/connecting to WiFi Direct?

**Comment by benzea** [comment]
Hmm, that won't be enough.

What you can do is disconnect the linux machine (and windows if you like, that doesn't matter). Then you should be able to run `iw dev mon0 set channel X` and cycle through the channels, moving forward every few seconds.

The windows laptop should be probing on all/most channels. The projector might just be listening and responding on a specific channel. But, with the above you should end up with frames from all channels, and then you should see things.

**Comment by joakim-tjernlund** [comment]
A coworker tried Microsoft Message Analyzer and sent me a dump. I cannot find any wifi direct there either.
I guess one have to do some special config for WiFi direct to work?

**Comment by benzea** [comment]
Maybe it is purely a WFDr2 device and the projector is connected to your local wifi AP?

**Comment by joakim-tjernlund** [comment]
Last I checked these projectors they were not connected our local wifi AP

**Comment by d-air1** [comment]
I'm also having trouble discovering all wifi display devices on my network. It won't pick up any of the chromecasts or tv's with built in chromecast/miracast support. It does however pickup roku devices.

**Comment by benzea** [comment]
@Dashon1 chromecast is not supported. Only Wi-Fi Display Revision 1 (a.k.a. Miracast).
