### ISSUE TITLE
F30 broken dependencies

### ISSUE THREAD

**Issue by beda17** [benzea/gnome-screencast#28]
I do not know where to report your copr repo issue. I am a newbie, please be patient with me.

Dependecies not met on F30 when installing from copr benzea/screencast:
Error: 
 Issue: conflicting requests
  - nothing provides gstreamer1-plugin-openh264 needed by gnome-screencast-0.1.0-0.20190306git887b4da3.fc30.x86_64

Thank you in advance

**Comment by KaltWulx** [comment]
Check this [](url)https://fedoraproject.org/wiki/OpenH264, run a dnf update and try it again.

**Comment by beda17** [comment]
Thank you, it solved the issue. Sorry for your time.
