### ISSUE TITLE
Fails with Smart TV LG WEBOS

### ISSUE THREAD

**Issue by xidoc** [benzea/gnome-screencast#30]
Hi !
It's not possible for me to connect my Ubuntu Laptop with WebOS (TV LG).
It's function on Windows but not on Ubuntu.
![Capture d’écran de 2019-05-13 11-17-45](https://user-images.githubusercontent.com/10847177/57610394-078dd280-7571-11e9-8057-7eca3fab4692.png)

**Comment by benzea** [comment]
Could you run with `G_MESSAGES_DEBUG=all gnome-network-displays` and paste the output here?

**Comment by C0rn3j** [comment]
Can confirm, tried on webOS 3.x and webOS 4.x.

[Full log from 4.x connection attempt](https://haste.rys.pw/raw/lupudijado) (seems to fail the same way on 3.x)

Highlight:
```
** (gnome-network-displays:14912): DEBUG: 13:20:08.674: An audiocodec has been selected: yes
Error from pulseaudio-source: Failed to connect stream: No such entity
Error from pulseaudio-source: Internal data stream error.
Warning from inter video sink: Pipeline construction is invalid, please add queues.
** (gnome-network-displays:14912): DEBUG: 13:20:11.620: Forcing a keyframe!
```

**Comment by antonvalletas** [comment]
I can connect to my LG WebOS LF592U most of the time, however the stream is about 1-2FPS (however audio is perfect) but crashes after 30-40 seconds of streaming. Anything I can try? I'm willing to help in testing

**Comment by C0rn3j** [comment]
That TV looks to be webOS 2.x and a different issue so posting the log mentioned above could help

**Comment by antonvalletas** [comment]
Here is a log where I got a succesful connection with 1-2 FPS, connected audio after around 5 seconds of starting to stream, and stream crashed 30 seconds after starting to stream.
[gnomenetdisplayslog1.txt](https://github.com/benzea/gnome-network-displays/files/3372150/gnomenetdisplayslog1.txt)

**Comment by benzea** [comment]
Uh, there seem to be different issues here.

 * `Error from pulseaudio-source: Internal data stream error` that @C0rn3j saw kinda sounds like a system without pulseaudio. This is not supported
 * Low framerate and then failing, sounds like various other issues that are already open here. It seems the QOS handling is still buggy

And the original bug might be something else entirely …

**Comment by C0rn3j** [comment]
I'm on Arch Linux and am definitely using PA.

**Comment by benzea** [comment]
@C0rn3j do you have the "Network-Displays" sink appear as a sound output when you launch gnome-network-displays? Is the `module-null-sink` loaded?

**Comment by C0rn3j** [comment]
Sink loaded yes
![image](https://user-images.githubusercontent.com/1641362/64131121-de66ab80-cdc6-11e9-98ac-5c03972211a8.png)

Module also
```
[0] % pactl list short modules | grep sink
13      module-always-sink
25      module-null-sink        sink_name=gnome_network_displays rate=48000 sink_properties=device.description="Network-Displays"device.class="sound"device.icon_name="network-wireless"
```
Debug log: https://haste.rys.pw/raw/ewuhavocej

**Comment by benzea** [comment]
So, the various issues that were named here have mostly been addressed (e.g. #20, i.e. the regular disconnect). The original bug report might be the same as #44, but it is unclear.

Closing for now. Feel free to open/re-open if there is more information about the original bug (and it is not the same as #44).
