### ISSUE TITLE
Can't get any devices to show up

### ISSUE THREAD

**Issue by C0rn3j** [benzea/gnome-screencast#31]
Using the git version on Arch Linux by means of [AUR/gnome-screencast-git](https://aur.archlinux.org/packages/gnome-screencast-git/)
![image](https://user-images.githubusercontent.com/1641362/58171175-a9aa6a80-7c95-11e9-8676-c729bb409260.png)

As a note am running it on KDE.

```
c0rn3j@Luxuria : ~
[130] % G_MESSAGES_DEBUG=all gnome-network-displays
(gnome-network-displays:16199): GLib-GIO-DEBUG: 13:25:21.673: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
(gnome-network-displays:16199): Gtk-DEBUG: 13:25:21.692: Connecting to session manager
(gnome-network-displays:16199): Gtk-DEBUG: 13:25:21.692: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned
(gnome-network-displays:16199): Gtk-DEBUG: 13:25:21.692: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned
** (gnome-network-displays:16199): DEBUG: 13:25:21.736: WFDP2PRegistry: Got NMClient
** (gnome-network-displays:16199): DEBUG: 13:25:21.737: NdScreencastPortal: Aquired Portal proxy
** (gnome-network-displays:16199): DEBUG: 13:25:21.737: task is: 0x55ea31cd49b0
** (gnome-network-displays:16199): DEBUG: 13:25:21.737: NdPulseaudio: Querying sink info by name
** (gnome-network-displays:16199): DEBUG: 13:25:21.758: NdPulseaudio: Sink does not exist yet, loading module
** (gnome-network-displays:16199): DEBUG: 13:25:21.758: NdScreencastPortal: Received CreateSession response
** (gnome-network-displays:16199): DEBUG: 13:25:21.758: simple variant lookup: /org/freedesktop/portal/desktop/session/1_1076/gtk1224956946
** (gnome-network-displays:16199): DEBUG: 13:25:21.761: NdScreencastPortal: Received SelectSource response
** (gnome-network-displays:16199): DEBUG: 13:25:21.762: NdPulseaudio: Module loaded, we are ready to grab audio! 
** (gnome-network-displays:16199): DEBUG: 13:25:21.763: NdScreencastPortal: Received Start response

** (gnome-network-displays:16199): WARNING **: 13:25:21.763: Error initing screencast portal: Failed to start streaming on portal session (response: 2)

** (gnome-network-displays:16199): WARNING **: 13:25:21.763: Falling back to X11! You need to fix your setup to avoid issues (XDG Portals and/or mutter screencasting support)!
```

**Comment by benzea** [comment]
Please verify that you have Network Manager 1.16 and wpa_supplicant with P2P wifi support.

**Comment by C0rn3j** [comment]
[0] % pacman -Q networkmanager wpa_supplicant
networkmanager 1.18.0-1
wpa_supplicant 2:2.8-1

How do I verify the latter?

As a note, I can get Miraclecast to work to the point of connecting to the device.

**Comment by benzea** [comment]
You could check `nmcli` and see if you have a `p2p-dev-XXX` device where XXX is the name of your normal wifi device.

**Comment by benzea** [comment]
Or run `gdbus call --system --dest fi.w1.wpa_supplicant1 --object-path /fi/w1/wpa_supplicant1 --method org.freedesktop.DBus.Properties.Get fi.w1.wpa_supplicant1 Capabilities` as root and see if p2p is in the list

**Comment by C0rn3j** [comment]
```
p2p-dev-wlp0s20u1: disconnected
        "p2p-dev-wlp0s20u1"
```

So that'd be yes.

Does NetworkManager need to be running for Screencast to work? I just tried starting it and trying again and I still didn't get anything, but I normally use systemd-networkd.

EDIT: Tried on my laptop which uses NM for a manager by default, and I could get it working. Got stuck on x264 though.

**Comment by benzea** [comment]
Hmm, really not sure what might be going on. Could you paste the output of `iw phy` please?

**Comment by benzea** [comment]
Oh, right. You Wi-Fi needs to be managed by network manager for this to work. If you do something weird like starting network manager, allowing it to manage your main wifi connection but also managing it otherwise, then this will probably simply not work.

**Comment by benzea** [comment]
Thinking the main issue was something odd happening with NetworkManager. Feel free to re-open, but I don't really see anything I can do here right now.

**Comment by C0rn3j** [comment]
Ah yeah, forgot to close this one, sorry. It was me not understanding I need to use NM for this project to work.
