### ISSUE TITLE
flatpak yml or json manifest support

### ISSUE THREAD

**Issue by trappedinspacetime** [benzea/gnome-screencast#33]
First of all thank you for developing this tool.
I am on Ubuntu 16.04 platform and some dependencies to build `gnome-screencast` fails.
Flatpak provides latest SDK libraries to build and run it in  my platform.
Would anybody help me prepare `.json` or `.yml` manifest to build it?

**Comment by benzea** [comment]
Sure, that seems reasonable. In general we will need the codecs in GStreamer and also access to the systems NetworkManager DBus interface for connection establishment.

**Comment by benzea** [comment]
Note that Ubuntu 16.04 *cannot* support this project as you need at least NetworkManager 1.16.

**Comment by trappedinspacetime** [comment]
@benzea Thank you for responding. Version of `NetworkManager` is `1.2.6` in my distro, so it fails to pass the requisitions. :(
I took a look at the `pitivi` flatpak, it provides some insight about how to make a `.json` build manifest file.
https://gitlab.gnome.org/GNOME/pitivi/tree/master/build/flatpak

**Comment by C0rn3j** [comment]
Note for OP - 18.04 has NM 1.10, only 19.04 has NM 1.16

**Comment by trappedinspacetime** [comment]
@benzea @C0rn3j would it break my system if I build latest version of `NetworkManager` from source?

**Comment by benzea** [comment]
It simply won't work, and probably won't even build.

**Comment by trappedinspacetime** [comment]
@benzea I built it succesfully, but I fear to install it.

**Comment by benzea** [comment]
Ah, right, NetworkManager. Right, if the install is correct, then I think it is unlikely to break. That said, you should make sure that you can downgrade again (e.g. by downloading the relevant packages before installing).

Please also note that you will need to update wpa_supplicant I suspect. It might work, but I am sure it will at least crash on every disconnect.

**Comment by benzea** [comment]
Really, a more modern live disk might be easier if you just want to test it.

**Comment by trappedinspacetime** [comment]
@benzea I installed and tested `NetworkManager`, it is running well, except it complains about `insufficient privileges` in lightdm login screen, but there is no problem in user session.

      NetworkManager --version 
      1.19.2
I wanted to install `gstreamer` to build `gnome-screen` but I hit [this](https://gitlab.freedesktop.org/gstreamer/gst-build/issues/15#note_165359) bug

**Comment by C0rn3j** [comment]
`do-release-upgrade`
You'll probably have an easier time by running at least the current LTS.

**Comment by trappedinspacetime** [comment]
@C0rn3j I have a custom, modified `Ubuntu 16.04` distro. I don't want to upgrade it for the time being.

**Comment by benzea** [comment]
I am sorry, but I don't have the time and energy to help you get this working on Ubuntu 16.04. It is unlikely to be simple and you are likely to create new issues when you do partial upgrades.
