### ISSUE TITLE
package x264 is not recognized as an encoder on Arch Linux

### ISSUE THREAD

**Issue by C0rn3j** [benzea/gnome-screencast#34]
```
** (gnome-network-displays:23400): ERROR **: 21:24:32.263: WFD: Did not find any usable H264 video encoder, missing dependencies!
```

```
[0] % pacman -Q x264       
x264 2:157.r72db4377-1


[133] % pacman -Ql x264                   
x264 /usr/
x264 /usr/bin/
x264 /usr/bin/x264
x264 /usr/include/
x264 /usr/include/x264.h
x264 /usr/include/x264_config.h
x264 /usr/lib/
x264 /usr/lib/libx264.so
x264 /usr/lib/libx264.so.157
x264 /usr/lib/pkgconfig/
x264 /usr/lib/pkgconfig/x264.pc
```

I've 'x264' installed, why would screencast possibly tell me it won't find an encoder? Tried on a laptop using both the intel GPU and AMD GPU with the same result.

**Comment by benzea** [comment]
You need the corresponding gstreamer plugins, not just the library. I am working on adding gnome-software integration to run an automatic install for missing and essential plugins.

I'll close this for now, as I think that is dealt with in other places.

**Comment by C0rn3j** [comment]
And which plugins would that be? Readme doesn't list any.

**Comment by benzea** [comment]
The gstreamer plugin is called x264.

**Comment by C0rn3j** [comment]
Seems to be in `gst-plugins-ugly` on Arch, I'll poke the AUR maintainer about it.
Now I seem to be hitting the webOS issue, will post there soon.
