### ISSUE TITLE
Does not give feedback when connection was cancelled by sink

### ISSUE THREAD

**Issue by cunidev** [benzea/gnome-screencast#4]
When I try to connect gnome-screencast to my Sharp TV, after one or two seconds of "Connecting..." my TV returns to display a "Ready for connection" message, as if the connection was refused. However, GNOME Screencast continues to display the "Establishing connection" dialog as if the connection was not refused.

My hypothesis is that the connection was refused, as GNOME Screencast continues showing that message indefinitely. I am on Fedora 29 Wayland

**Comment by cunidev** [comment]
Not so helpful, but somewhat helpful GIF: https://gfycat.com/OldOnlyAsp
Connection is "refused" by my TV about a second after connecting it.

**Comment by cunidev** [comment]
The sequence of messages on my TV is approximately this:

0.0s: Ready
0.0s: (choose sink on PC, press Connect)
1.0s: Connecting
1.2s: Connected
1.5s: Ready

**Comment by benzea** [comment]
Ah, yes. I believe i have fixed that bug. Let me update the fedora package today/tomorrow (I'll update the ticket then). Could you try it again once I have done so?

Basically, I just didn't register the callback correctly to detect that NetworkManager failed to connect.

**Comment by cunidev** [comment]
Sure.

**Comment by benzea** [comment]
I submitted the build, unfortunately it seems that the runners are stuck currently:

  https://copr.fedorainfracloud.org/coprs/benzea/screencast/build/854902/

**Comment by cunidev** [comment]
That was solved, but now it crashes when I reclick it after connection refused...

```
[r@aragorn ~]$ gnome-screencast

** (gnome-screencast:6825): CRITICAL **: 20:40:19.750: screencast_wfd_p2p_sink_sink_start_stream: assertion 'self->state == SCREENCAST_SINK_STATE_DISCONNECTED' failed

** (gnome-screencast:6825): WARNING **: 20:40:19.750: ScreencastWindow: Could not start streaming!

(gnome-screencast:6825): GLib-GObject-WARNING **: 20:40:19.750: invalid (NULL) pointer instance

(gnome-screencast:6825): GLib-GObject-CRITICAL **: 20:40:19.750: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(gnome-screencast:6825): GLib-GObject-WARNING **: 20:40:19.750: invalid (NULL) pointer instance

(gnome-screencast:6825): GLib-GObject-CRITICAL **: 20:40:19.750: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(gnome-screencast:6825): GLib-GObject-WARNING **: 20:40:19.750: invalid (NULL) pointer instance

(gnome-screencast:6825): GLib-GObject-CRITICAL **: 20:40:19.750: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
**
ERROR:../src/screencast-sink-row.c:86:screencast_sink_row_set_property: assertion failed: (sink_row->sink != NULL)
Aborted (core dump creato)

```

**Comment by benzea** [comment]
Woops, simple mistake actually :)

When that happens an error panel is supposed to be shown. That forces you to "stop" the streaming so that it is back in the `DISCONNECTED` state rather than `ERROR` state before "starting" it again.

Anyway, new build is done:
  https://copr.fedorainfracloud.org/coprs/benzea/screencast/build/855550/

Did you ever manage to get a working connection?

**Comment by cunidev** [comment]
No, not so far. DNF shows me no updates, maybe it'll take a while to propagate

**Comment by cunidev** [comment]
I've just installed the update. While connection to both my TV and my Android phone ("Miracast Sink" app) still fails, at least the "Error" screen is displayed after about 5-10 seconds. I'd suggest to make that window look more like an "error", as the minimal change from the "connecting" screen makes it pretty difficult to distinguish graphically.

No messages were shown in the log, is there any way to debug the issue in detail?

**Comment by cunidev** [comment]
Wait, wait, wait. I haven't installed the "p2p patches" as far as I'm aware (and found that out just now), does that count?

My NetworkManager version is: `1.15.2-22042.6345e7726b.fc29`

**Comment by benzea** [comment]
Nah, that is fine. You are getting a patched NetworkManager from my copr repository. However, you need to disable selinux unfortunately. i.e. run `setenforce 0` as root.

If you do not do that, then the DHCP server that is required for P2P operation will not start.

**Comment by cunidev** [comment]
I disabled that just after installing it the first time some days ago.

**Comment by benzea** [comment]
Hm, OK, so we likely have some other issue.

Could you re-run in the terminal while setting `G_MESSAGES_DEBUG=all`. i.e. with:

```
G_MESSAGES_DEBUG=all gnome-screencast
```

Then connect, wait for it to fail, and post the output here. As a next step, I may want a tcpdump of the P2P device.

Also, could you post the output of the following commands:

```
iw phy
iw dev
```

**Comment by benzea** [comment]
I am wondering about the `iw phy`/`iw dev` output, because I am
wondering if we need to deal with network cards that are not able to
deal with being connected to an AP and P2P network at the same time.

**Comment by cunidev** [comment]
```
[r@aragorn ~]$ G_MESSAGES_DEBUG=all gnome-screencast
(gnome-screencast:3463): dconf-DEBUG: 10:39:14.545: watch_fast: "/org/gnome/desktop/interface/" (establishing: 0, active: 0)
(gnome-screencast:3463): dconf-DEBUG: 10:39:14.546: watch_fast: "/org/gnome/settings-daemon/peripherals/mouse/" (establishing: 0, active: 0)
(gnome-screencast:3463): dconf-DEBUG: 10:39:14.546: watch_fast: "/org/gnome/desktop/sound/" (establishing: 0, active: 0)
(gnome-screencast:3463): dconf-DEBUG: 10:39:14.546: watch_fast: "/org/gnome/desktop/privacy/" (establishing: 0, active: 0)
(gnome-screencast:3463): dconf-DEBUG: 10:39:14.546: watch_fast: "/org/gnome/desktop/wm/preferences/" (establishing: 0, active: 0)
(gnome-screencast:3463): dconf-DEBUG: 10:39:14.546: watch_fast: "/org/gnome/settings-daemon/plugins/xsettings/" (establishing: 0, active: 0)
(gnome-screencast:3463): dconf-DEBUG: 10:39:14.546: watch_fast: "/org/gnome/desktop/a11y/" (establishing: 0, active: 0)
(gnome-screencast:3463): dconf-DEBUG: 10:39:14.548: watch_established: "/org/gnome/desktop/interface/" (establishing: 1)
(gnome-screencast:3463): dconf-DEBUG: 10:39:14.548: watch_established: "/org/gnome/settings-daemon/peripherals/mouse/" (establishing: 1)
(gnome-screencast:3463): dconf-DEBUG: 10:39:14.548: watch_established: "/org/gnome/desktop/sound/" (establishing: 1)
(gnome-screencast:3463): dconf-DEBUG: 10:39:14.548: watch_established: "/org/gnome/desktop/privacy/" (establishing: 1)
(gnome-screencast:3463): dconf-DEBUG: 10:39:14.548: watch_established: "/org/gnome/desktop/wm/preferences/" (establishing: 1)
(gnome-screencast:3463): dconf-DEBUG: 10:39:14.548: watch_established: "/org/gnome/settings-daemon/plugins/xsettings/" (establishing: 1)
(gnome-screencast:3463): dconf-DEBUG: 10:39:14.548: watch_established: "/org/gnome/desktop/a11y/" (establishing: 1)
(gnome-screencast:3463): Gtk-DEBUG: 10:39:14.591: Connecting to session manager
** (gnome-screencast:3463): DEBUG: 10:39:14.708: WFDP2PRegistry: Found a new device, creating provider
** (gnome-screencast:3463): DEBUG: 10:39:14.708: WfdP2PProvider: Discover is now set to 1
** (gnome-screencast:3463): DEBUG: 10:39:14.708: ScreencastPortal: Aquired Portal proxy
** (gnome-screencast:3463): DEBUG: 10:39:14.708: task is: 0x7fb29400c9b0
** (gnome-screencast:3463): DEBUG: 10:39:14.711: WFDP2PRegistry: Got NMClient
** (gnome-screencast:3463): DEBUG: 10:39:14.714: ScreencastPortal: Received CreateSession response
** (gnome-screencast:3463): DEBUG: 10:39:14.714: simple variant lookup: /org/freedesktop/portal/desktop/session/1_83/gtk1388561821
** (gnome-screencast:3463): DEBUG: 10:39:14.714: ScreencastPulseaudio: Querying sink info by name
** (gnome-screencast:3463): DEBUG: 10:39:14.714: ScreencastPulseaudio: Error querying sink info
** (gnome-screencast:3463): DEBUG: 10:39:14.714: ScreencastPulseaudio: Got a sink info for the expected name
** (gnome-screencast:3463): DEBUG: 10:39:14.716: ScreencastPortal: Received SelectSource response
** (gnome-screencast:3463): DEBUG: 10:39:18.299: ScreencastPortal: Received Start response
** (gnome-screencast:3463): DEBUG: 10:39:18.299: Got a stream with node ID: 19
** (gnome-screencast:3463): DEBUG: 10:39:24.508: WFDP2PProvider: Found a new sink with peer 0x556a1e032210 on device 0x556a1dfce330
** (gnome-screencast:3463): DEBUG: 10:39:24.508: SinkList: Adding a sink
** (gnome-screencast:3463): DEBUG: 10:39:25.754: WfdP2PProvider: Discover is now set to 0
** (gnome-screencast:3463): DEBUG: 10:39:25.799: ScreencastWfdP2PSink: Got P2P connection
** (gnome-screencast:3463): DEBUG: 10:39:25.800: Got state change notification from streaming sink to state SCREENCAST_SINK_STATE_WAIT_SOCKET
** (gnome-screencast:3463): DEBUG: 10:39:38.184: WfdServer: Finalize
** (gnome-screencast:3463): DEBUG: 10:39:38.184: Got state change notification from streaming sink to state SCREENCAST_SINK_STATE_ERROR
** (gnome-screencast:3463): DEBUG: 10:39:40.044: Got state change notification from streaming sink to state SCREENCAST_SINK_STATE_DISCONNECTED
** (gnome-screencast:3463): DEBUG: 10:39:40.044: WfdP2PProvider: Discover is now set to 1
** (gnome-screencast:3463): DEBUG: 10:39:41.317: MetaSink: No usable sink is left, object has become invalid.
(gnome-screencast:3463): dconf-DEBUG: 10:39:41.318: sync
[r@aragorn ~]$ iw phy
Wiphy phy0
	max # scan SSIDs: 16
	max scan IEs length: 195 bytes
	max # sched scan SSIDs: 16
	max # match sets: 16
	max # scan plans: 2
	max scan plan interval: 7200
	max scan plan iterations: 100
	Retry short limit: 7
	Retry long limit: 4
	Coverage class: 0 (up to 0m)
	Device supports RSN-IBSS.
	Device supports AP-side u-APSD.
	Device supports T-DLS.
	Supported Ciphers:
		* WEP40 (00-0f-ac:1)
		* WEP104 (00-0f-ac:5)
		* TKIP (00-0f-ac:2)
		* CCMP-128 (00-0f-ac:4)
		* CMAC (00-0f-ac:6)
		* CMAC-256 (00-0f-ac:13)
		* GMAC-128 (00-0f-ac:11)
		* GMAC-256 (00-0f-ac:12)
	Available Antennas: TX 0x3 RX 0x3
	Configured Antennas: TX 0x3 RX 0x3
	Supported interface modes:
		 * IBSS
		 * managed
		 * AP
		 * monitor
		 * mesh point
		 * P2P-client
		 * P2P-GO
		 * P2P-device
	Band 1:
		Capabilities: 0x19ef
			RX LDPC
			HT20/HT40
			SM Power Save disabled
			RX HT20 SGI
			RX HT40 SGI
			TX STBC
			RX STBC 1-stream
			Max AMSDU length: 7935 bytes
			DSSS/CCK HT40
		Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
		Minimum RX AMPDU time spacing: 8 usec (0x06)
		HT TX/RX MCS rate indexes supported: 0-15
		Bitrates (non-HT):
			* 1.0 Mbps
			* 2.0 Mbps (short preamble supported)
			* 5.5 Mbps (short preamble supported)
			* 11.0 Mbps (short preamble supported)
			* 6.0 Mbps
			* 9.0 Mbps
			* 12.0 Mbps
			* 18.0 Mbps
			* 24.0 Mbps
			* 36.0 Mbps
			* 48.0 Mbps
			* 54.0 Mbps
		Frequencies:
			* 2412 MHz [1] (20.0 dBm)
			* 2417 MHz [2] (20.0 dBm)
			* 2422 MHz [3] (20.0 dBm)
			* 2427 MHz [4] (20.0 dBm)
			* 2432 MHz [5] (20.0 dBm)
			* 2437 MHz [6] (20.0 dBm)
			* 2442 MHz [7] (20.0 dBm)
			* 2447 MHz [8] (20.0 dBm)
			* 2452 MHz [9] (20.0 dBm)
			* 2457 MHz [10] (20.0 dBm)
			* 2462 MHz [11] (20.0 dBm)
			* 2467 MHz [12] (20.0 dBm) (no IR)
			* 2472 MHz [13] (20.0 dBm) (no IR)
			* 2484 MHz [14] (disabled)
	Band 2:
		Capabilities: 0x19ef
			RX LDPC
			HT20/HT40
			SM Power Save disabled
			RX HT20 SGI
			RX HT40 SGI
			TX STBC
			RX STBC 1-stream
			Max AMSDU length: 7935 bytes
			DSSS/CCK HT40
		Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
		Minimum RX AMPDU time spacing: 8 usec (0x06)
		HT TX/RX MCS rate indexes supported: 0-15
		VHT Capabilities (0x339071b2):
			Max MPDU length: 11454
			Supported Channel Width: neither 160 nor 80+80
			RX LDPC
			short GI (80 MHz)
			TX STBC
			SU Beamformee
			MU Beamformee
			RX antenna pattern consistency
			TX antenna pattern consistency
		VHT RX MCS set:
			1 streams: MCS 0-9
			2 streams: MCS 0-9
			3 streams: not supported
			4 streams: not supported
			5 streams: not supported
			6 streams: not supported
			7 streams: not supported
			8 streams: not supported
		VHT RX highest supported: 0 Mbps
		VHT TX MCS set:
			1 streams: MCS 0-9
			2 streams: MCS 0-9
			3 streams: not supported
			4 streams: not supported
			5 streams: not supported
			6 streams: not supported
			7 streams: not supported
			8 streams: not supported
		VHT TX highest supported: 0 Mbps
		Bitrates (non-HT):
			* 6.0 Mbps
			* 9.0 Mbps
			* 12.0 Mbps
			* 18.0 Mbps
			* 24.0 Mbps
			* 36.0 Mbps
			* 48.0 Mbps
			* 54.0 Mbps
		Frequencies:
			* 5180 MHz [36] (20.0 dBm) (no IR)
			* 5200 MHz [40] (20.0 dBm) (no IR)
			* 5220 MHz [44] (20.0 dBm) (no IR)
			* 5240 MHz [48] (20.0 dBm) (no IR)
			* 5260 MHz [52] (20.0 dBm) (no IR, radar detection)
			* 5280 MHz [56] (20.0 dBm) (no IR, radar detection)
			* 5300 MHz [60] (20.0 dBm) (no IR, radar detection)
			* 5320 MHz [64] (20.0 dBm) (no IR, radar detection)
			* 5500 MHz [100] (27.0 dBm) (no IR, radar detection)
			* 5520 MHz [104] (27.0 dBm) (no IR, radar detection)
			* 5540 MHz [108] (27.0 dBm) (no IR, radar detection)
			* 5560 MHz [112] (27.0 dBm) (no IR, radar detection)
			* 5580 MHz [116] (27.0 dBm) (no IR, radar detection)
			* 5600 MHz [120] (27.0 dBm) (no IR, radar detection)
			* 5620 MHz [124] (27.0 dBm) (no IR, radar detection)
			* 5640 MHz [128] (27.0 dBm) (no IR, radar detection)
			* 5660 MHz [132] (27.0 dBm) (no IR, radar detection)
			* 5680 MHz [136] (27.0 dBm) (no IR, radar detection)
			* 5700 MHz [140] (27.0 dBm) (no IR, radar detection)
			* 5720 MHz [144] (disabled)
			* 5745 MHz [149] (disabled)
			* 5765 MHz [153] (disabled)
			* 5785 MHz [157] (disabled)
			* 5805 MHz [161] (disabled)
			* 5825 MHz [165] (disabled)
			* 5845 MHz [169] (disabled)
			* 5865 MHz [173] (disabled)
	Supported commands:
		 * new_interface
		 * set_interface
		 * new_key
		 * start_ap
		 * new_station
		 * new_mpath
		 * set_mesh_config
		 * set_bss
		 * authenticate
		 * associate
		 * deauthenticate
		 * disassociate
		 * join_ibss
		 * join_mesh
		 * remain_on_channel
		 * set_tx_bitrate_mask
		 * frame
		 * frame_wait_cancel
		 * set_wiphy_netns
		 * set_channel
		 * set_wds_peer
		 * tdls_mgmt
		 * tdls_oper
		 * start_sched_scan
		 * probe_client
		 * set_noack_map
		 * register_beacons
		 * start_p2p_device
		 * set_mcast_rate
		 * connect
		 * disconnect
		 * channel_switch
		 * set_qos_map
		 * set_multicast_to_unicast
	Supported TX frame types:
		 * IBSS: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * managed: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * AP: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * AP/VLAN: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * mesh point: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * P2P-client: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * P2P-GO: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * P2P-device: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
	Supported RX frame types:
		 * IBSS: 0x40 0xb0 0xc0 0xd0
		 * managed: 0x40 0xd0
		 * AP: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
		 * AP/VLAN: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
		 * mesh point: 0xb0 0xc0 0xd0
		 * P2P-client: 0x40 0xd0
		 * P2P-GO: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
		 * P2P-device: 0x40 0xd0
	WoWLAN support:
		 * wake up on disconnect
		 * wake up on magic packet
		 * wake up on pattern match, up to 22 patterns of 1-134 bytes,
		   maximum packet offset 114 bytes
		 * wake up on network detection, up to 16 match sets
	software interface modes (can always be added):
		 * monitor
	valid interface combinations:
		 * #{ managed } <= 2, #{ AP, mesh point, P2P-client, P2P-GO } <= 2, #{ P2P-device } <= 1,
		   total <= 4, #channels <= 1
		 * #{ managed } <= 2, #{ P2P-client } <= 2, #{ AP, mesh point, P2P-GO } <= 1, #{ P2P-device } <= 1,
		   total <= 4, #channels <= 2
		 * #{ managed } <= 1, #{ IBSS } <= 1,
		   total <= 2, #channels <= 1
	HT Capability overrides:
		 * MCS: ff ff ff ff ff ff ff ff ff ff
		 * maximum A-MSDU length
		 * supported channel width
		 * short GI for 40 MHz
		 * max A-MPDU length exponent
		 * min MPDU start spacing
	Device supports TX status socket option.
	Device supports HT-IBSS.
	Device supports SAE with AUTHENTICATE command
	Device supports scan flush.
	Device supports AP scan.
	Device supports per-vif TX power setting
	Driver supports full state transitions for AP/GO clients
	Driver supports a userspace MPM
	Driver/device bandwidth changes during BSS lifetime (AP/GO mode)
	Device supports static SMPS
	Device supports configuring vdev MAC-addr on create.
	Device supports VHT-IBSS.
[r@aragorn ~]$ iw dev
phy#0
	Unnamed/non-netdev interface
		wdev 0x5
		addr 9c:b6:d0:8d:02:9f
		type P2P-device
		txpower 0.00 dBm
	Interface wlp2s0
		ifindex 2
		wdev 0x1
		addr 9c:b6:d0:8d:02:9f
		ssid r
		type managed
		channel 11 (2462 MHz), width: 40 MHz, center1: 2452 MHz
		txpower 20.00 dBm

```

**Comment by cunidev** [comment]
Just for information, using it with the dummy sink works properly, just delayed by 3s or so

**Comment by cunidev** [comment]
The strangest aspect of this is that my TV says "connected" for a very short time (0.5s?), while displaying no buffer of course, which makes me think something is actually closing the connection just after initiating it for no apparently good reason.

**Comment by benzea** [comment]
Not really strange, that confirms what the log says. The step that is failing is that the TV should connect to the local RTSP server. It looks like it never tries to do this, and then simply disconnects and NM will then kill the connection after 5 seconds. I am wondering about two things:

 * Do you maybe have a firewall configured?
 * Could you check the journal for errors?

If you have wireshark or similar installed, then you could try getting a dump of the traffic. That can be a bit of a pain though, as new interface is created dynamically (something like `p2p-wlp2s0-XX`).

Alternatively, the following line should start capture 0.1 seconds after the p2p device is created (which is generally good enough. You will get a file `/tmp/p2p-connection-dump.pcap`. To use, you will need to install `tcpdump`.

```
interface=""; while [ -z "$interface" ]; do interface=$( ls /sys/class/net/ | grep -- p2p- ); sleep 0.1; done; echo $interface; tcpdump -i "$interface" -w /tmp/p2p-connection-dump.pcap
```

b.t.w. `gnome-screencast` already introduces a lag of about 600ms, the other 2.5s lag are probably simply your player buffering.

**Comment by cunidev** [comment]
No firewall I think, it's a vanilla Fedora connected to my 32" Sharp TV directly with no AP in between. I'll try sniffing the interface with the command you gave me tonight as my Fedora laptop is at home. 

My TV is actually not an expensive one, and I wouldn't be surprised if there were any bugs in its Miracast implementation (though I only had problems with a Nexus 6P on it so far). 

I can also reproduce the issue using an Android phone as sink ("miracast sink" on Play Store), if you could try to reproduce it with something like that we could blame either the network card or the sink.

**Comment by benzea** [comment]
Ah, hmm; maybe I could find an android phone and try that (I personally don't have one readily available).

**Comment by cunidev** [comment]
Or you could live boot a somewhat modern PC using Android-x86, if the wireless card is supported there should be little difference with an Android phone. The Play Store login takes 1-2 minutes but I'm sure online APKs are available for such simple, free apps

**Comment by benzea** [comment]
Hmm, yeah that could work. Though I probably will not get around to try that until late next week unfortunately.

**Comment by benzea** [comment]
Hm, nah, android x86 doesn't work with those apps (they just crash).

**Comment by cunidev** [comment]
Temporarily hosted here: https://transfer.sh/14mmse/p2p-connection-dump.pcap

**Comment by cunidev** [comment]
That is the dump from my Sharp TV, has nothing to do with Android btw

**Comment by cunidev** [comment]
```
[root@aragorn r]# interface=""; while [ -z "$interface" ]; do interface=$( ls /sys/class/net/ | grep -- p2p- ); sleep 0.1; done; echo $interface; tcpdump -i "$interface" -w /tmp/p2p-connection-dump.pcap
p2p-wlp2s0-2
tcpdump: p2p-wlp2s0-2: That device is not up
```

**Comment by benzea** [comment]
Thanks for that!

Oh, I actually had a thought what the issue may be. With WFD you are supposed to setup some information elements on the WiFi frames, this is used by the sink to decide on the port to connect to. I am currently not setting this but rely on the sink to use the default port.

I'll attach a small python script tomorrow which sets these WFD IEs (simply running it before trying to connect will be enough).

**Comment by benzea** [comment]
Hmm, looking at the dump, it seems like a fundamental issue. i.e. the P2P connection is never properly established.

I assume "aragorn" is your computer?

One more question, if you connect with another machine, are you prompted for a PIN or does it simply connect?

I am considering two reasons now. One would be that we need to connect using the pin method (rather than push button). The other is still setting the WFD IEs correctly.

If I could just test it here, I'll need to try and find a Sharp Smart TV, it seems. :-/

**Comment by cunidev** [comment]
> I assume "aragorn" is your computer?

Yeah, my laptop :P

> One more question, if you connect with another machine, are you prompted for a PIN or does it simply connect?

It just connects.


> If I could just test it here, I'll need to try and find a Sharp Smart TV, it seems. :-/

IMO it's the network card or something client side rather than the TV itself, but if it is, then it's not worth it. Someone among GNOME devs/testers will certainly have one if you ask them.

**Comment by benzea** [comment]
OK, so the PBC method is used and just works with the TV, so no issue there.

To try setting the WFD IEs, run the following command as root. It should be enough to run it once before starting `gnome-screencast`:
```
gdbus call --system --dest fi.w1.wpa_supplicant1 --object-path /fi/w1/wpa_supplicant1 --method org.freedesktop.DBus.Properties.Set fi.w1.wpa_supplicant1 WFDIEs "<@ay [0x00, 0x00, 0x06, 0x00, 0x90, 0x1c, 0x44, 0x00, 0xc8]>"
```

I also created a ([set-wfd-ies.py](https://benjamin.sipsolutions.net/set-wfd-ies.py)) script, but that is quite a lot of code, and does exactly the same thing in the end. 

After that, I am out of ideas for now, and also think it is best if I look into it myself. I have kept you busy enough with trying things :)

**Comment by cunidev** [comment]
```
[r@aragorn ~]$ gnome-screencast

** (gnome-screencast:3596): WARNING **: 14:25:46.326: Resolution 29 not found in table VESA, but was in suppliments 0x3FFFFFFF


** (gnome-screencast:3596): WARNING **: 14:25:46.327: Resolution 29 not found in table VESA, but was in suppliments 0x3FFFFFFF


** (gnome-screencast:3596): WARNING **: 14:25:46.327: WfdClient: No resolution found, falling back to standard FullHD resolution.
```

Works now! I don't know if the warnings above are meaningful, but at least it streams everything. WiFi works obviously slower but at the same time, and a YouTube video is properly streamed. No audio but I may have not installed the needed codecs (and that's a different issue). So WFD IEs should be set by gnome-screencaster apparently, and we have a proper "issue".

**Comment by benzea** [comment]
Nice! Unfortunately that will require some fixes in NetworkManager and gnome-screencast, but good to know how to get it working! :)

The first two warnings are a buggy implementation in the sharp TV (it claims to support resolutions that don't exist in the specification).

The other warning is currently normal, as `gnome-screencast` currently ignores the list that is supported by the sink and this riggers FullHD to be always selected right now.

**Comment by benzea** [comment]
Thanks! Closing this issue in favour of issue #6.

**Comment by benzea** [comment]
Ah, btw. for sound you will need to go into the sound panel and switch the output to "GNOME-Screencast". It will not be the default pulse audio sink, so unless you do that switch no audio will ever be transmitted.
