### ISSUE TITLE
WiFi Direct instead of WiFi P2P

### ISSUE THREAD

**Issue by cmurf** [benzea/gnome-screencast#42]
I see in GNOME Network Display the message "No Wi-Fi P2P adapters found" and when I look up Wi-Fi P2P I see it was initially called that, but they settled on Wi-Fi Direct.
https://en.wikipedia.org/wiki/Wi-Fi_Direct

And also found a typo on the copr page:
https://copr.fedorainfracloud.org/coprs/benzea/screencast/
- dnf install gnome-newtork-displays
+ dnf install gnome-network-displays

**Comment by benzea** [comment]
Fixed the typo. Yeah, the terms are used interchangeably. The NetworkManager API actually now uses P2P (so does wpa_supplicant).

I don't have a strong opinion on those strings to be honest. It could be confusing though as they are likely to show up as "P2P" in other places.
