### ISSUE TITLE
feature request: dev package

### ISSUE THREAD

**Issue by yonderblue** [benzea/gnome-screencast#43]
I understand the project is still mainly in development but any chance we could get a nightly dev .deb or something along those lines? Could help get more to test if nothing else.

**Comment by benzea** [comment]
I just merged a flatpak manifest, so that would be a good way of providing such a development snapshot. The copr builds are only updated irregularly currently, and the Fedora package should come along (but obviously also not a development snapshot).

**Comment by benzea** [comment]
So, looks like what I will do is moving the project to GNOME gitlab, and then create a CI pipeline there that will build a Flatpak regularly.

**Comment by tartley** [comment]
Did that happen? Or is this repo still the main one?

**Comment by benzea** [comment]
No, so far this is the main one.

**Comment by papermache** [comment]
Second this. WPA_Supplicant is hard enough to set up and users are missing the opportunity to connect to Android over Wifi Direct.

**Comment by b1oki** [comment]
Maybe snap package or AppImage, spent 3 days resolving dependencies (Linux Mint 19.3 based on Ubuntu 18.04)

**Comment by edurenye** [comment]
I think should be a gnome-extension as I said here: #119 
The could be easily enabled with just one click from https://extensions.gnome.org/

**Comment by benzea** [comment]
> I think should be a gnome-extension as I said here: #119
> The could be easily enabled with just one click from https://extensions.gnome.org/

That doesn't solve dependency issues.
