### ISSUE TITLE
LG webOS failure to connect

### ISSUE THREAD

**Issue by torvitas** [benzea/gnome-screencast#49]
Hi, sorry to dig this one up again but it looks like I am having a very similar error like #41 although stopping firewalld did not help.
I am also on fedora 30 with your COPR and on LG webOS.

- The TV is found as a sink.
- The TV says "[no name] connecting".
- Then the TV says detecting Miracast signal.
- Then the Connection fails.

[NetworkManager.log](https://github.com/benzea/gnome-network-displays/files/3441753/NetworkManager.log)
[gnome-network-display.log](https://github.com/benzea/gnome-network-displays/files/3441754/gnome-network-display.log)
[dmesg.log](https://github.com/benzea/gnome-network-displays/files/3441755/dmesg.log)

**Comment by torvitas** [comment]
Well right now I had a test where it actually said "starting to stream" (on both sides) before it eventually fails. The only difference to yesterday is that I did not have debugging enabled.

Update:
I can reproduce this new behaviour, although I have no clue what changed since yesterday. Maybe the new patch release of the firmware of this TV improved the situation.

So now it goes like this:
- TV found as Sink
- Connecting
  - TV says: [no name] connecting
  - TV  says: Detecting Miracast signal
  - TV says: Miracast starts streaming.
  - PC says: Starting to stream.
  - TV goes to black screen
  - TV goes back to where it was before

[NetworkManager.1.log](https://github.com/benzea/gnome-network-displays/files/3446439/NetworkManager.1.log)
[gnome-network-display.1.log](https://github.com/benzea/gnome-network-displays/files/3446440/gnome-network-display.1.log)

**Comment by benzea** [comment]
Seems like we are ending up dropping all frames. i.e. same issues as others.

Something must be broken with my QOS handling to ensure real-time processing, but I am not sure what so far :)

**Comment by benzea** [comment]
Could you try running with `NETWORK_DISPLAYS_H264_ENC=openh264` and see if that helps? When done, the `Found x264enc for video encoding.` should disappear and the `openh264` encoder will be used rather than `x264enc` which might make a difference.

**Comment by torvitas** [comment]
I'll try that as soon as I am at home. Thanks for the heads up.

**Comment by benzea** [comment]
No response, could you maybe test a current version and report back if the issues persist?

Though unfortunately the F31 package is not quite up to date currently (for some reason my package update got stuck).

**Comment by torvitas** [comment]
Hi, sorry for the late response. I just build the current master but sadly, other than that I get some keep-alive messages in debug log after it drops all the QOS packets, the behaviour did not change.
[gnome-network-display.log](https://github.com/benzea/gnome-network-displays/files/4025886/gnome-network-display.log)

**Comment by benzea** [comment]
Hmm, sounds really similar to #78. Maybe try what I suggested in https://github.com/benzea/gnome-network-displays/issues/78#issuecomment-570681755? i.e. either grab a full tcpdump of the RTSP connection or run with `GST_DEBUG=rtspclient:5 `.
