### ISSUE TITLE
Microsoft Wireless Adapter v2 not working

### ISSUE THREAD

**Issue by archit3kt** [benzea/gnome-screencast#50]
Hi, I'm trying to connect to my Microsoft Wireless Adapter v2 (Miracast and WiDi compatible, firmware 2.0.8381) with gnome-network-displays, didn't succeed so far

firewall is off when experimenting

I got the ND_SINK_STATE_ERROR

It would be really great to make it work since this dongle is widely used, I'd gladly help for further debugging

Working like a charm on Windows 10

Using actually up to date manjaro liniux

Here is the debug session :

G_MESSAGES_DEBUG=all gnome-network-displays                                                            
(gnome-network-displays:17343): GLib-GIO-DEBUG: 18:04:20.078: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
(gnome-network-displays:17343): Gtk-DEBUG: 18:04:20.186: Connecting to session manager
(gnome-network-displays:17343): Gtk-DEBUG: 18:04:20.187: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned
** (gnome-network-displays:17343): DEBUG: 18:04:20.273: WFDP2PRegistry: Found a new device, creating provider
** (gnome-network-displays:17343): DEBUG: 18:04:20.273: WFDP2PProvider: Found a new sink with peer 0x557d7ba29aa0 on device 0x557d7b321f80
** (gnome-network-displays:17343): DEBUG: 18:04:20.273: WFDP2PProvider: Found a new sink with peer 0x557d7b4d95c0 on device 0x557d7b321f80
** (gnome-network-displays:17343): DEBUG: 18:04:20.273: WfdP2PProvider: Discover is now set to 1
** (gnome-network-displays:17343): DEBUG: 18:04:20.273: SinkList: Adding a sink
** (gnome-network-displays:17343): DEBUG: 18:04:20.274: SinkList: Adding a sink
** (gnome-network-displays:17343): DEBUG: 18:04:20.281: NdScreencastPortal: Aquired Portal proxy
** (gnome-network-displays:17343): DEBUG: 18:04:20.283: task is: 0x557d7b9f2400
** (gnome-network-displays:17343): DEBUG: 18:04:20.297: NdScreencastPortal: Received CreateSession response

** (gnome-network-displays:17343): WARNING **: 18:04:20.297: Error initing screencast portal: Failed to create portal session (response: 2)

** (gnome-network-displays:17343): WARNING **: 18:04:20.297: Falling back to X11! You need to fix your setup to avoid issues (XDG Portals and/or mutter screencasting support)!
** (gnome-network-displays:17343): DEBUG: 18:04:20.297: WFDP2PRegistry: Got NMClient
** (gnome-network-displays:17343): DEBUG: 18:04:20.301: NdPulseaudio: Querying sink info by name
** (gnome-network-displays:17343): DEBUG: 18:04:20.301: NdPulseaudio: Error querying sink info
** (gnome-network-displays:17343): DEBUG: 18:04:20.301: NdPulseaudio: Got a sink info for the expected name
** (gnome-network-displays:17343): DEBUG: 18:04:22.394: Found openh264enc for video encoding.
** (gnome-network-displays:17343): DEBUG: 18:04:22.394: Found x264enc for video encoding.
** (gnome-network-displays:17343): DEBUG: 18:04:22.394: Found fdkaacenc for audio encoding.
** (gnome-network-displays:17343): DEBUG: 18:04:22.395: Found avenc_aac for audio encoding.
** (gnome-network-displays:17343): DEBUG: 18:04:22.395: Found faac for audio encoding.
** (gnome-network-displays:17343): DEBUG: 18:04:22.395: Got state change notification from streaming sink to state ND_SINK_STATE_WAIT_P2P
** (gnome-network-displays:17343): DEBUG: 18:04:22.397: WfdP2PProvider: Discover is now set to 0
** (gnome-network-displays:17343): DEBUG: 18:04:22.493: NdWfdP2PSink: Got P2P connection
** (gnome-network-displays:17343): DEBUG: 18:04:22.495: Found openh264enc for video encoding.
** (gnome-network-displays:17343): DEBUG: 18:04:22.495: Found x264enc for video encoding.
** (gnome-network-displays:17343): DEBUG: 18:04:22.495: Found fdkaacenc for audio encoding.
** (gnome-network-displays:17343): DEBUG: 18:04:22.495: Found avenc_aac for audio encoding.
** (gnome-network-displays:17343): DEBUG: 18:04:22.495: Found faac for audio encoding.
** (gnome-network-displays:17343): DEBUG: 18:04:22.496: Got state change notification from streaming sink to state ND_SINK_STATE_WAIT_SOCKET
** (gnome-network-displays:17343): DEBUG: 18:04:30.981: WFDP2PProvider: Peer removed
** (gnome-network-displays:17343): DEBUG: 18:04:30.981: MetaSink: No usable sink is left, object has become invalid.
** (gnome-network-displays:17343): DEBUG: 18:04:30.982: SinkList: Removing a sink
** (gnome-network-displays:17343): DEBUG: 18:05:07.492: WfdServer: Finalize
** (gnome-network-displays:17343): DEBUG: 18:05:07.492: Got state change notification from streaming sink to state ND_SINK_STATE_ERROR
** (gnome-network-displays:17343): DEBUG: 18:05:10.983: WFDP2PProvider: Peer removed
** (gnome-network-displays:17343): DEBUG: 18:05:10.983: MetaSink: No usable sink is left, object has become invalid.
** (gnome-network-displays:17343): DEBUG: 18:05:10.984: SinkList: Removing a sink
** (gnome-network-displays:17343): DEBUG: 18:05:12.688: Got state change notification from streaming sink to state ND_SINK_STATE_DISCONNECTED
** (gnome-network-displays:17343): DEBUG: 18:05:12.688: WfdP2PProvider: Discover is now set to 1

**Comment by benzea** [comment]
It looks like the sink never connects or even disconnects after it cannot establish a connection.

`WAIT_SOCKET` is the last state, and that happens after the WiFi Direct connection is established, but before the TV will receive a DHCP address from us.

Could you check the NetworkManager logs whether anything odd is happening there? Also, is the TV maybe showing an error or similar?

**Comment by Algram** [comment]
@benzea I think the issue is, that Microsoft extended the Miracast protocol for its version 2 adapter. The miraclecast project has an open WIP PR that implements those extensions: https://github.com/albfan/miraclecast/pull/136

Maybe the gnome-network-displays also needs to support those extensions? The version 2 adapter is quite common now.

Thanks for your work!

**Comment by benzea** [comment]
IIRC, the main difference is support for reporting/setting a number of MS specific options. It is easy to add those to `gnome-network-displays`. And yeah, that might improve the situation in general.

However that is *not* the issue that is visible in the above debug messages. Those show, that the MS adapter never opens the TCP/IP connection to our server. And that clearly shows that we are failing even before any MS specific options are processed.

**Comment by benzea** [comment]
Issue #69 suggests that the MS v2 adapter is mostly working. Except for the old keep-alive issue, or whatever it is, t hat I have never been able to understand/reproduce unfortunately.

I really don't know what the problem here is. I would suspect that e.g. the DHCP server does not work, or some other weird things happen on the lower networking layer (outside of the scope of this piece of software).

I can try to answer more questions, but I don't really see what I can do for this bug specifically. For the timeout issue, I might try to get my hands on an MS v2 adapter.
