### ISSUE TITLE
Cant connect to anycast dongle (miracast)

### ISSUE THREAD

**Issue by biji** [benzea/gnome-screencast#52]
After showing this:

 Establishing connection to sin ... then Error

how to find error log?

**Comment by benzea** [comment]
Please run with `G_MESSAGES_DEBUG=all`, i.e. type

```
G_MESSAGES_DEBUG=all gnome-network-displays
```

in a terminal. Then paste the output here.

**Comment by benzea** [comment]
Closing as no further information has been provided.

I learned one more thing. It might help to set `MACAddressPolicy=none` in systemd (`/etc/systemd/newtork/*`).
