### ISSUE TITLE
installation mint 19.2 (ubuntu 18.04)

### ISSUE THREAD

**Issue by ghost** [benzea/gnome-screencast#53]
hi

sorry, i'm a bit of a noob. i can't see anywhere in the readme how to install it on linux mint 19.2 (ubuntu 18.04). can anyone please guide me through the installation for ubuntu?

thanks in advance

**Comment by warrenc5** [comment]
have a look at https://github.com/benzea/gnome-network-displays/issues/38

**Comment by benzea** [comment]
You need a rather new NetworkManager (1.16), so it is not unlikely that it cannot even run if it is based on Ubuntu 18.04.

Anyway, I can't help you directly with Linux mint unfortunately. It is probably better to ask in distribution specific channels. The installation should be pretty standard in most regards.

**Comment by ghost** [comment]
Thanks for taking the time to respond. Unfortunately I doubt that it can run on 18.04.

You have done a fantastic job of making it possible to use miracast on Linux, truly revolutionary work!
