### ISSUE TITLE
Feature Request: MS-MICE

### ISSUE THREAD

**Issue by faupol3** [benzea/gnome-screencast#58]
Is there any possibility to add a feature like the following?
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-mice/9598ca72-d937-466c-95f6-70401bb10bdb
Basically it allows for miracast connection over LAN instead of WiFi-Direct if I understood correctly. Sounds like a nice feature to have.
Either way this is already an awesome project. Hope it gets included in gnome by default :)

**Comment by benzea** [comment]
It is possible in principle, in fact, gnome-network-displays has been designed internally to be able to add further protocols. And, in particular Miracast revision 2 would likely be a candidate for this, or e.g. Chromecast (see #18).

That said, I will likely not be able to dedicated any time to implement such a feature myself.
