### ISSUE TITLE
Installation deletes default pulseaudio sink

### ISSUE THREAD

**Issue by Evidlo** [benzea/gnome-screencast#59]
I installed and uninstalled `gnome-network-displays` and my default system output device is no longer visible.  Now I just have a dummy output and no soundcard.

**Comment by Evidlo** [comment]
Deleting the pulseaudio user configs seems to have fixed it: 

```
sudo killall pulseaudio
rm -r ~/.config/pulse/*
rm -r ~/.pulse*
sudo shutdown -h now
```

https://askubuntu.com/questions/835512/sound-card-has-disappeared-from-sound-settings-dialog

**Comment by benzea** [comment]
Huh? All `gnome-network-displays` does is add a dummy null sink that it can monitor to grab audio from. And even that should disappear again after restarting pulseaudio in my experience.

So, I don't really know what is going on here. Maybe Ubuntu has something that tries to store the pulseaudio config at logout and that is messing things up?

**Comment by benzea** [comment]
So, personally, I have seen weird stuff like this happening sometimes. What generally fixed it for me was to just kill pulseaudio.

To be honest, I think it just randomly happened at the time you were playing with gnome-network-displays. Anyway, closing. Feel free to reopen if you can properly reproduce the issue.
