### ISSUE TITLE
Implement WFD IE setting for the source interface

### ISSUE THREAD

**Issue by benzea** [benzea/gnome-screencast#6]
As was found out by @cunidev in issue #4, we need to set the WFD IEs correctly for some sinks to work. At least a few sinks work fine without doing so, but in these elements e.g. the port to connect to is set.

This will need changes on the network manager side. For anyone affected by this, you can run the following command (as root) before starting `gnome-screencast` to work around this issue:

```
gdbus call --system --dest fi.w1.wpa_supplicant1 --object-path /fi/w1/wpa_supplicant1 --method org.freedesktop.DBus.Properties.Set fi.w1.wpa_supplicant1 WFDIEs "<@ay [0x00, 0x00, 0x06, 0x00, 0x90, 0x1c, 0x44, 0x00, 0xc8]>"
```

**Comment by benzea** [comment]
See https://gitlab.freedesktop.org/NetworkManager/NetworkManager/issues/125 for the required NetworkManager support.

**Comment by benzea** [comment]
@cunidev. FYI, I have a fix and it is build in the copr repository. The code is not yet on the main branch as the NetworkManager patches are still pending upstream review.

I hope that with this the Sharp TV will simply work.

**Comment by cunidev** [comment]
Probably yes, thanks for all your work!

**Comment by cunidev** [comment]
Seems to work flawlessly from the copr repo, while the code from `master` still needs the command to be issued. I guess this is the expected behaviour, so feel free to close this. Thanks!

**Comment by benzea** [comment]
Great! Thanks a lot for testing.

I will close the bug once I merged the patch into master. I was just waiting for the NM patches to be merged (which happened a few minutes ago).
