### ISSUE TITLE
Casting screen from my Dell Inspiron 5558 laptop to TV (Brand Name: Haier)

### ISSUE THREAD

**Issue by MuhammadAliKhan1** [benzea/gnome-screencast#61]
I have a builtin Miracast on my TV. After trying miracle-cast and trying to configure it to work with my TV (failed), I tried to give your code a try. After installing dependencies and trying to configure it (took me one hour), I was able to cast my laptop screen to my TV. Although the casting was very much laggy,  your code was very easy to build and install. Now I'm trying to stream my audio to the TV using PulseAudio as mentioned in your readme.   
![image](https://user-images.githubusercontent.com/41667480/65373425-d9469f00-dc96-11e9-97d0-5d24414df429.png)

I'm getting a bunch of errors in my terminal, and I don't know what they are.

Laptop Specifications in the picture below.
![image](https://user-images.githubusercontent.com/41667480/65373462-393d4580-dc97-11e9-9703-bfbe7c3671b8.png)

Also after some time, the screencasting hangs and a critical error message is displayed.
![untitled](https://user-images.githubusercontent.com/41667480/65373543-49a1f000-dc98-11e9-9124-ef9a4b3a4f9a.png)

**Comment by benzea** [comment]
Hmm, maybe the VAAPI encoder isn't working properly for some reason?

Try running with `NETWORK_DISPLAYS_H264_ENC=openh264enc src/gnome-network-displays`. It might also be worth to enable debugging output using `G_MESSAGES_DEBUG=all`

**Comment by benzea** [comment]
Closing as there was no reply for a long time.
