### ISSUE TITLE
How do you enable p2p?

### ISSUE THREAD

**Issue by dchinmay2** [benzea/gnome-screencast#64]
My adapter (TL-WN725N) supports WiFi Direct. Its driver is part of the kernel.
I have networkmanager 1.20.2-1 and wpa_supplicant 2:2.9-1.
Yet ```nmcli``` shows this:
```        "Realtek RTL8188EUS"
        wifi (r8188eu), C0:25:E9:26:87:B0, hw, mtu 1500
        ip4 default, ip6 default
        inet4 192.168.1.8/24
        route4 0.0.0.0/0
        route4 192.168.1.0/24
        inet6 fe80::2a2b:4035:2d08:f5cf/64
        route6 fe80::/64
        route6 ::/0
        route6 ff00::/8

**Comment by ArnoldSchiller** [comment]
```
iw wlan0 interface add p2p0 type managed
nmcli connection edit type wifi-p2p con-name REMOTEDISPLAY
set wifi-p2p.peer MACADRESSFROMTHEREMOTEDISPLAY  
set wifi-p2p.wps-method pbc
set connection.autoconnect no
save
quit
```
But this only works if (in my case a rtl8192se)
``` 
wpa_cli p2p_find
Selected interface 'wlan0'
OK
```
It doesn't work on one of my devices, so it looks like (in this case a  iwlwifi Ultimate-N 6300) 
```
wpa_cli p2p_find
Selected interface 'wlan0'
FAIL
```

**Comment by ArnoldSchiller** [comment]
Since today I have a TP-LINK TL-WN821N version 6 - The thing has a RTL8192EU built in and not like version1,2 or 3 an ath9k - p2p only works when wpa_supplicant loads the nl80211 driver. 

To ensure this, in /etc/network/interfaces I have
```
iface wlan1 inet dhcp
      wpa-driver nl80211,wext
      wpa-conf /etc/wpa_supplicant/wpa1.conf
```
and allowed the NetworkManager in the networkmanager.conf ifupdown.
```
[main]
plugins=ifupdown,keyfile
```
Oh yes and the driver of TP-Link itself doesn't work under Kernel 5.2 but this one here 
https://github.com/clnhub/rtl8192eu-linux

**Comment by ArnoldSchiller** [comment]
Note to the above post, the RTL8192EU does not run stable in p2p-mode. lwfinger also does not intend to support it. That's why I returned the stick. ID 7392:7811 Edimax Technology Co., Ltd EW-7811Un 802.11n Wireless Adapter [Realtek RTL8188CUS] ran with the same configuration out of the box

**Comment by benzea** [comment]
@ChiDal what does `iw phy` say?

**Comment by dchinmay2** [comment]
> @ChiDal what does `iw phy` say?

Blank

**Comment by dchinmay2** [comment]
> ```
> iw wlan0 interface add p2p0 type managed
> nmcli connection edit type wifi-p2p con-name REMOTEDISPLAY
> set wifi-p2p.peer MACADRESSFROMTHEREMOTEDISPLAY  
> set wifi-p2p.wps-method pbc
> set connection.autoconnect no
> save
> quit
> ```
> 
> But this only works if (in my case a rtl8192se)
> 
> ```
> wpa_cli p2p_find
> Selected interface 'wlan0'
> OK
> ```
> 
> It doesn't work on one of my devices, so it looks like (in this case a iwlwifi Ultimate-N 6300)
> 
> ```
> wpa_cli p2p_find
> Selected interface 'wlan0'
> FAIL
> ```

```wpa_cli p2p_find``` gives:
 ```Failed to connect to non-global ctrl_ifname: (nil)  error: No such file or directory```

**Comment by dchinmay2** [comment]
I have the exact same error on Arch and rawhide

**Comment by benzea** [comment]
> > @ChiDal what does `iw phy` say?
> 
> Blank

To be honest, I don't really believe that … it should list all phy's and their capabilities. And you definitely have some phy's otherwise you wouldn't have wifi.

**Comment by dchinmay2** [comment]
> > > @ChiDal what does `iw phy` say?
> > 
> > 
> > Blank
> 
> To be honest, I don't really believe that … it should list all phy's and their capabilities. And you definitely have some phy's otherwise you wouldn't have wifi.

![Screenshot from 2019-11-09 10-40-38](https://user-images.githubusercontent.com/36493671/68523328-68436100-02af-11ea-8f1c-2c9301481c7f.png)

**Comment by ArnoldSchiller** [comment]
@ChiDal sudo su and then iw phy perhaps your user hasn't the right to access the wifi-device

**Comment by benzea** [comment]
It does not seem like one needs root privileges to query the phy information. I am a bit lost as to what this means. I mean, is the wifi adapter not managed through nl80211 but wext or something ancient like that?

**Comment by dchinmay2** [comment]
> @ChiDal sudo su and then iw phy perhaps your user hasn't the right to access the wifi-device

Still blank

**Comment by benzea** [comment]
But, what does `iw dev` show then?

**Comment by dchinmay2** [comment]
> But, what does `iw dev` show then?

Blank too

**Comment by ArnoldSchiller** [comment]
Very strange
```
cd /sys/devices/
find . | grep phy80211
```

**Comment by benzea** [comment]
Well … the explanation would be that the device still uses a `wext` driver. Which is ancient, and probably unsupported really …

**Comment by benzea** [comment]
To be honest, I am assuming that something is odd with that specific wifi device. I'll close this, as I don't know where to continue looking and everything kinda looks to me like it cannot work with that specific wifi device.

**Comment by dchinmay2** [comment]
@benzea Pinged you so that you get notifications as the issue is closed.
So it is indeed `wext` and I found this in realtek docs:
![image](https://user-images.githubusercontent.com/36493671/77400489-2a009700-6da3-11ea-91e2-331332823fa8.png)

The command worked without any errors (I tried both n=1 and n=3 from here:
![image](https://user-images.githubusercontent.com/36493671/77400661-6e8c3280-6da3-11ea-8f96-bb25e3fe4b49.png)
) .Also `iwpriv` lists `p2p_set`, `p2p_get` and `p2p_get2` in available private ioctls
But `p2p_find` still `FAIL`s in wpa_cli

**Comment by benzea** [comment]
@ChiDal, I do understand that it is a pain, but I don't think we can support this at all.

From a gnome-network-displays point of view, it is an issue for NetworkManager or lower in the stack. However, wext is really old and has been replaced by newer and better interfaces. I don't think there is any interest in trying to properly support it.

The various projects might accept patches. But you are probably better off just forgetting about this hardware unfortunately.
