### ISSUE TITLE
Video works fine but lags about a second

### ISSUE THREAD

**Issue by solstag** [benzea/gnome-screencast#65]
Ni!

I have this device sold as [Yehua Anycast M4 Plus](https://www.amazon.com/Anycast-Display-Wireless-Adapter-Miracast/dp/B0771CCSH5/).

I got video working on a Fedora 30 system (haven't looked at audio since I don't need it).

However, the casted screen always lags for a little less then a second, making it alright for static presentations, but not good enough to watch a movie.

I have tried changing the hardcoded resolution in `src/wfd/wfd-client.c` (as well as enabling resolution negotiation) but nothing seems to change. The only noticeable change was when changing refresh rate from 30 to 60, regardless of resolution, the lag increased.

`$ nmcli` gives me:
```
p2p-dev-wlp2s0: connecté to Wi-Fi P2P Peer 02:0F:06:41:D6:18
        "p2p-dev-wlp2s0"
        wifi-p2p, hw, iface p2p-wlp2s0-0, mtu 1500
        inet4 10.42.0.1/24
        route4 10.42.0.0/24
        inet6 fe80::b26c:c6b8:3e70:5f70/64
        route6 fe80::/64
        route6 ff00::/8
```
And here's the full log for:
[`$ G_MESSAGES_DEBUG=all gnome-network-displays`](https://gist.github.com/solstag/03d7cb7e2cb86572dd5b0886ad5e3738)

Any ideas on how to debug this?

Thanks a lot, and abraços!

**Comment by benzea** [comment]
Yeah, this is by design. Basically, if we don't do this then audio tends to drop out in certain situations (i.e. the video sometimes lags for complex frames and then the audio drops out).

**Comment by benzea** [comment]
To be honest, I don't think you can get video watching with audio direct and video casted to be in sync properly.

**Comment by solstag** [comment]
Hi @benzea and sorry I didn't answer before, it got lost in my inbox.

I think I didn't properly explain my issue. The video on screen is not in sync with the audio coming out of my PC. Are you saying that is by design ?

Thanks again, ale

**Comment by benzea** [comment]
> The video on screen is not in sync with the audio coming out of my PC. Are you saying that is by design?

Not just "by design". Technically impossible to fix even :)

**Comment by solstag** [comment]
I see. I guess the best one could achieve is to manually lag the audio too, to get it in sync.

Thanks for your answers =]
