### ISSUE TITLE
Add extra debugging

### ISSUE THREAD

**Issue by edurenye** [benzea/gnome-screencast#66]
Add extra-debugging to be able to fix the following issues:
#20 
#65 
https://github.com/benzea/gnome-network-displays/issues/19#issuecomment-546299011

**Comment by gforcada** [comment]
I would welcome this addition as well, I have no idea, nor debugging output to understand why my fedora 31 can not connect to my miracast device :confused: 

Any debugging tips? :thinking: 

Thanks for creating this project!! :bowing_man:

**Comment by gforcada** [comment]
Ok, so I see that there is `G_MESSAGES_DEBUG=all` that can be used. :sweat_smile:

**Comment by benzea** [comment]
Well, issue #20 has probably been solved (i.e. 6afa893). But that is not what Gil is seeing (Hi Gil!).

One problem there is that the issue may be on other levels, so not sure I can add much more debugging info even.

**Comment by benzea** [comment]
To be honest, I think there is already quite a lot. Maybe more helpful would be a some instructions on how to pinpoint errors when connecting (which can be spread across NetworkManager and wpa_supplicant).

**Comment by gforcada** [comment]
Yeah, that's the problem I have, the dummy display (`NETWORK_DISPLAYS_DUMMY`) works fine, I can see the my miracast device, the connection is started (the TV shows that something is going on) but although I have `G_MESSAGES_DEBUG=all` I can only see that there was a timeout :confused:
