### ISSUE TITLE
Quick how-to

### ISSUE THREAD

**Issue by qdrop17** [benzea/gnome-screencast#67]
Hello.

Do you mind writing a couple of lines on how to install this on Ubuntu? I am a bit lost with only the source-code to be honest.

Any help is highly appreciated. I want to switch to Ubuntu, but we often have meetings that require this screencasting functionality.

**Comment by huats** [comment]
Hello I had the same kind of questionning.

I end up doing

git clone 
cd https://github.com/benzea/gnome-network-displays.git
cd gnome-network-displays
meson build
cd build
ninja

Then launch src/gnome-network-displays

**Comment by henriquedesousa** [comment]
As always when trying to compile stuff on Linux, there's always some weird dependency that cannot be found. After installing a lot of packages:

```
  sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
  sudo apt-get install libgstrtspserver-1.0-dev gstreamer1.0-rtsp
  sudo apt-get install libgtk-3-dev
  sudo apt-get install libnm-dev 
```
I'm getting: 

`src/meson.build:30:0: ERROR: Invalid version of dependency, need 'libnm' ['>= 1.15'] found '1.10.6'.`

Using Mint 19.2 which is based on Ubuntu 18.04 LTS. If someone can compile and provide a package, that would be appreciated.

**Comment by reece15** [comment]
> As always when trying to compile stuff on Linux, there's always some weird dependency that cannot be found. After installing a lot of packages:
> 
> ```
>   sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
>   sudo apt-get install libgstrtspserver-1.0-dev gstreamer1.0-rtsp
>   sudo apt-get install libgtk-3-dev
>   sudo apt-get install libnm-dev 
> ```
> 
> I'm getting:
> 
> `src/meson.build:30:0: ERROR: Invalid version of dependency, need 'libnm' ['>= 1.15'] found '1.10.6'.`
> 
> Using Mint 19.2 which is based on Ubuntu 18.04 LTS. If someone can compile and provide a package, that would be appreciated.

can you fix it?

**Comment by benzea** [comment]
This package will never be usable on those old distributions.

**Comment by fvmsantos** [comment]
any solution?

**Comment by benzea** [comment]
Update your computer to a recent distribution?

**Comment by onetuser** [comment]
Had the same problems with meson itself and libnm in the end.
Ubuntu 18.04.4 LTS. Sorry, I think the latest LTS is recent enough.
Could install it on Ubuntu 19 though.

**Comment by paultelles** [comment]
Ubuntu 19.10 with X11 and OpenH264 v2.0.0 works great for video streaming to a LG TV. I haven't tried audio streaming or Wayland.
