### ISSUE TITLE
Missing dependency creating intervideosink

### ISSUE THREAD

**Issue by HTWDD-SN** [benzea/gnome-screencast#68]
In Ubuntu 19.10 the following behavior is shown:

- Miracast device is listed in a dialog
- Connection is established
- Creating video link fails because of missing dependency while creating intervideosink, unfortunately no info is provided which dependency is missing, x264, x265 and faac  is installed 

src/gnome-network-displays 

** (gnome-network-displays:31129): WARNING **: 13:03:43.854: Error calling DBus method during Screencast portal initialization: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop

** (gnome-network-displays:31129): WARNING **: 13:03:43.854: Error initing screencast portal: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop

** (gnome-network-displays:31129): WARNING **: 13:03:43.854: Screencasting portal is unavailable! It is required to select the monitor to stream!

** (gnome-network-displays:31129): WARNING **: 13:03:43.854: Falling back to X11! You need to fix your setup to avoid issues (XDG Portals and/or mutter screencasting support)!

** (gnome-network-displays:31129): WARNING **: 13:04:57.309: WfdClient: No resolution found, falling back to standard FullHD resolution.

** (gnome-network-displays:31129): ERROR **: 13:04:57.369: Error creating intervideosink, missing dependency!
Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)

**Comment by HTWDD-SN** [comment]
The problem with debug messages:

 $ G_MESSAGES_DEBUG=all ./gnome-network-displays 
(gnome-network-displays:3436): GLib-GIO-DEBUG: 16:16:59.012: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
(gnome-network-displays:3436): Gtk-DEBUG: 16:16:59.186: Connecting to session manager
** (gnome-network-displays:3436): DEBUG: 16:16:59.311: WFDP2PRegistry: Found a new device, creating provider
** (gnome-network-displays:3436): DEBUG: 16:16:59.311: WfdP2PProvider: Discover is now set to 1
** (gnome-network-displays:3436): DEBUG: 16:16:59.315: NdScreencastPortal: Aquired Portal proxy
** (gnome-network-displays:3436): DEBUG: 16:16:59.315: task is: 0x55dd25ac6990
** (gnome-network-displays:3436): DEBUG: 16:16:59.316: WFDP2PRegistry: Got NMClient

** (gnome-network-displays:3436): WARNING **: 16:16:59.316: Error calling DBus method during Screencast portal initialization: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop

** (gnome-network-displays:3436): WARNING **: 16:16:59.316: Error initing screencast portal: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop

** (gnome-network-displays:3436): WARNING **: 16:16:59.316: Screencasting portal is unavailable! It is required to select the monitor to stream!

** (gnome-network-displays:3436): WARNING **: 16:16:59.316: Falling back to X11! You need to fix your setup to avoid issues (XDG Portals and/or mutter screencasting support)!
** (gnome-network-displays:3436): DEBUG: 16:16:59.322: NdPulseaudio: Querying sink info by name
** (gnome-network-displays:3436): DEBUG: 16:16:59.323: NdPulseaudio: Sink does not exist yet, loading module
** (gnome-network-displays:3436): DEBUG: 16:16:59.423: NdPulseaudio: Module loaded, we are ready to grab audio! 
** (gnome-network-displays:3436): DEBUG: 16:17:03.418: WFDP2PProvider: Found a new sink with peer 0x55dd258c74f0 on device 0x55dd258af160
** (gnome-network-displays:3436): DEBUG: 16:17:03.419: SinkList: Adding a sink
** (gnome-network-displays:3436): DEBUG: 16:17:09.632: Found x264enc for video encoding.
** (gnome-network-displays:3436): DEBUG: 16:17:09.632: Found vaapih264enc for video encoding.
** (gnome-network-displays:3436): DEBUG: 16:17:09.632: Found avenc_aac for audio encoding.
** (gnome-network-displays:3436): DEBUG: 16:17:09.633: Got state change notification from streaming sink to state ND_SINK_STATE_WAIT_P2P
** (gnome-network-displays:3436): DEBUG: 16:17:09.635: WfdP2PProvider: Discover is now set to 0
** (gnome-network-displays:3436): DEBUG: 16:17:09.689: NdWfdP2PSink: Got P2P connection
** (gnome-network-displays:3436): DEBUG: 16:17:09.698: Found x264enc for video encoding.
** (gnome-network-displays:3436): DEBUG: 16:17:09.698: Found vaapih264enc for video encoding.
** (gnome-network-displays:3436): DEBUG: 16:17:09.698: Found avenc_aac for audio encoding.
** (gnome-network-displays:3436): DEBUG: 16:17:09.699: Got state change notification from streaming sink to state ND_SINK_STATE_WAIT_SOCKET
** (gnome-network-displays:3436): DEBUG: 16:17:15.849: NdWfdP2PSink: Got client connection
** (gnome-network-displays:3436): DEBUG: 16:17:15.850: Got state change notification from streaming sink to state ND_SINK_STATE_WAIT_STREAMING
** (gnome-network-displays:3436): DEBUG: 16:17:16.389: WfdClient: OPTIONS querying done
** (gnome-network-displays:3436): DEBUG: 16:17:16.390: WFD query params
** (gnome-network-displays:3436): DEBUG: 16:17:16.476: WfdClient: GET_PARAMS done
** (gnome-network-displays:3436): DEBUG: 16:17:16.476: Add audio codec to params:
** (gnome-network-displays:3436): DEBUG: 16:17:16.476: WfdAudioCodec: LPCM, 3, latency: 0
** (gnome-network-displays:3436): DEBUG: 16:17:16.476: Add audio codec to params:
** (gnome-network-displays:3436): DEBUG: 16:17:16.476: WfdAudioCodec: AAC, 1, latency: 0
** (gnome-network-displays:3436): DEBUG: 16:17:16.476: Add audio codec to params:
** (gnome-network-displays:3436): DEBUG: 16:17:16.476: WfdAudioCodec: AC3, 0, latency: 0
** (gnome-network-displays:3436): DEBUG: 16:17:16.476: Add codec to params:
** (gnome-network-displays:3436): DEBUG: 16:17:16.477: WfdVideoCodec:
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * profile: 2
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * level: 4
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * native: 1920x1080 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.477: Supported resolutions:
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * 800x480 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * 800x480 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * 854x480 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * 854x480 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * 864x480 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * 864x480 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * 640x360 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * 640x360 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * 960x540 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * 960x540 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * 848x480 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * 848x480 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * 640x480 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * 720x480 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * 720x576 50p
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * 1280x720 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * 1280x720 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * 1920x1080 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * 1290x720 25p
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * 1280x720 50p
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * 1920x1080 25p
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * 1280x720 24p
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * 1920x1080 25p
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * 800x600 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * 800x600 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * 1024x768 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * 1024x768 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * 1152x864 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * 1152x864 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * 1280x768 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.477:  * 1280x768 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * 1280x800 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * 1280x800 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * 1360x768 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * 1360x768 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * 1366x768 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * 1366x768 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * 1280x1024 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * 1440x900 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * 1440x900 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * 1600x900 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * 1600x900 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * 1680x1024 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * 1680x1050 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.478: Add codec to params:
** (gnome-network-displays:3436): DEBUG: 16:17:16.478: WfdVideoCodec:
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * profile: 1
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * level: 4
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * native: 1920x1080 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.478: Supported resolutions:
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * 800x480 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * 800x480 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * 854x480 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * 854x480 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * 864x480 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * 864x480 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * 640x360 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * 640x360 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * 960x540 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * 960x540 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * 848x480 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * 848x480 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * 640x480 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * 720x480 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * 720x576 50p
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * 1280x720 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.478:  * 1280x720 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.479:  * 1920x1080 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.479:  * 1290x720 25p
** (gnome-network-displays:3436): DEBUG: 16:17:16.479:  * 1280x720 50p
** (gnome-network-displays:3436): DEBUG: 16:17:16.479:  * 1920x1080 25p
** (gnome-network-displays:3436): DEBUG: 16:17:16.479:  * 1280x720 24p
** (gnome-network-displays:3436): DEBUG: 16:17:16.479:  * 1920x1080 25p
** (gnome-network-displays:3436): DEBUG: 16:17:16.479:  * 800x600 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.479:  * 800x600 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.479:  * 1024x768 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.479:  * 1024x768 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.479:  * 1152x864 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.479:  * 1152x864 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.479:  * 1280x768 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.479:  * 1280x768 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.479:  * 1280x800 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.479:  * 1280x800 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.479:  * 1360x768 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.479:  * 1360x768 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.479:  * 1366x768 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.479:  * 1366x768 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.479:  * 1280x1024 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.479:  * 1440x900 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.479:  * 1440x900 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.479:  * 1600x900 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.479:  * 1600x900 60p
** (gnome-network-displays:3436): DEBUG: 16:17:16.479:  * 1680x1024 30p
** (gnome-network-displays:3436): DEBUG: 16:17:16.479:  * 1680x1050 30p

** (gnome-network-displays:3436): WARNING **: 16:17:16.479: WfdClient: No resolution found, falling back to standard FullHD resolution.
** (gnome-network-displays:3436): DEBUG: 16:17:16.479: selected resolution 1920, 1080 @30
** (gnome-network-displays:3436): DEBUG: 16:17:16.485: WfdClient: SET_PARAMS done
** (gnome-network-displays:3436): DEBUG: 16:17:16.491: WfdClient: Initialization done!
** (gnome-network-displays:3436): DEBUG: 16:17:16.492: use x11: 1

** (gnome-network-displays:3436): ERROR **: 16:17:16.502: Error creating intervideosink, missing dependency!
Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)

**Comment by benzea** [comment]
And, which part of `Error creating intervideosink, missing dependency` is not clear? What is missing is the `intervideosink` gstreamer element. Part of the `inter` plugin.

**Comment by grigio** [comment]
I'm having the same error @HTWDD-SN did you find a solution?
On Ubuntu 20.04
```
GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.ScreenCast”
```

**Comment by benzea** [comment]
@grigio, that is not an error … it just means that you will get the X11 fallback (which cannot handle multiple monitors properly).
