### ISSUE TITLE
Streaming shows black screen after installing audio drivers

### ISSUE THREAD

**Issue by cunidev** [benzea/gnome-screencast#7]
Worked (somewhat) properly before, but after installing gstreamer "bad-nonfree" plugins from RPMfusion (for audio support) I get only a black screen with those warnings:

```
(gnome-screencast:3663): GLib-GObject-WARNING **: 16:22:53.447: g_object_set_is_valid_property: object class 'GstX264Enc' has no property named 'max-rc-lookahead'
Warning from pulseaudio-source: Impossibile registrare l'audio a velocità adeguata
```

Translated: "Can't record audio at appropriate speed"

**Comment by cunidev** [comment]
Interestingly enough, some very short pieces of audio can be heard from the sink (still the same Sharp TV). Could it be a matter of bandwidth?

**Comment by benzea** [comment]
Oops, could be a few things, but I need to get around to debugging the x264enc usage. Should be a relatively easy fix in the end, but that will really need to wait avout a week :)

What happend is that you installed the x264enc encoder plugin for H264. gnome-screencast is now prefering that encoder. I had added the support, assumed it was better than openh264, but never managed to properly test that encoder.

I don't see an easy way to work around it by preventing gstreamer from detecting the plugin unfortunately.

Benjamin

**Comment by cunidev** [comment]
> Should be a relatively easy fix in the end, but that will really need to wait avout a week :)

No problem! Nothing urgent with it :)

**Comment by benzea** [comment]
> No problem! Nothing urgent with it :)

Thanks again for all the testing. This has been really useful for me!

**Comment by cunidev** [comment]
No problem, really! Thanks for your patience. I wish I knew more about Miracast/wireless stuff to help you coding too, but unfortunately I don't

**Comment by benzea** [comment]
Alright, should be fixed now.

Turns out we ended up sending a color format that is not supported

**Comment by cunidev** [comment]
It works! Thanks for your awesome work :D
