### ISSUE TITLE
[Feature Request] iwd support

### ISSUE THREAD

**Issue by ghost** [benzea/gnome-screencast#72]
Hello! It looks like [iwd](https://git.kernel.org/pub/scm/network/wireless/iwd.git) is getting more support now. It would be great if it was suported as a backend option - either wpa_supplicant or iwd. I was unable to find if it supports p2p functionality yet, but I hope it is so, because 1.0 release was not so far ago.

**Comment by benzea** [comment]
This is something that would need to be implemented in NetworkManager. gnome-network-displays just creates a NetworkManager connection on the fly.

**Comment by ghost** [comment]
NetworkManager already supports iwd backend. Maybe iwd itself should be updated to use p2p mode(if its not)

**Comment by benzea** [comment]
But NetworkManager does not support P2P with the iwd backend. I wrote the part that supports wpa_supplicant, but iwd was never a priority from my side.
