### ISSUE TITLE
Cannot close window (build from latest git)

### ISSUE THREAD

**Issue by micw** [benzea/gnome-screencast#83]
I have built from git do get the latest version. When I try to close the window, it hangs and shows on the console:

```
(gnome-network-displays:74948): GLib-GIO-CRITICAL **: 20:23:14.089: g_task_return_error_if_cancelled: assertion '!task->ever_returned' failed
```

**Comment by benzea** [comment]
You know, it is generally helpful to know what you are doing. "closing window" is rather meaningless, as there is a lot of state and the question about *when* you are trying to close the window is kind of important.

**Comment by micw** [comment]
Sorry, I thought there's only one (I did never ever pass that one ;-) ) It's the very first where I should be able to select the device.

**Comment by micw** [comment]
This is a regression from v0.90.2. Happens without portal

**Comment by micw** [comment]
git-bisected to:
[a8014cc54c6ff9d184c3bc3b93b2374f1ecfac7d] window: Cancel operations and free data in finalize

**Comment by micw** [comment]
After commenting out
```
g_cancellable_cancel (self->cancellable);
```
it works again.

**Comment by benzea** [comment]
"works"
