### ISSUE TITLE
Gnome-network-displays does not work with current Network Manager (1.22.x)

### ISSUE THREAD

**Issue by micw** [benzea/gnome-screencast#84]
While debugging for #82 it turned out that the reason is that gnome-network-displays is not compatible with current Network Manager version (1.22.4 in my case).
- a p2p scan is never triggered (bug in network manager, see https://gitlab.freedesktop.org/NetworkManager/NetworkManager/merge_requests/399), a workaround is to start the scan manually (e.g. using https://raw.githubusercontent.com/wertarbyte/hostap/master/wpa_supplicant/examples/p2p/p2p_find.py or by running `gdbus call --system --dest fi.w1.wpa_supplicant1 --object-path /fi/w1/wpa_supplicant1/Interfaces/0 --method fi.w1.wpa_supplicant1.Interface.P2PDevice.Find '{}'` ) while gnome-network-displays is running
- When trying to connect to a device, gnome-network-displays segfaults with `(gnome-network-displays:163112): libnm-CRITICAL **: 22:56:46.796: ((../NetworkManager/libnm/nm-client.c:3733)): assertion '<dropped>' failed`

**Comment by benzea** [comment]
@micw, it would probably be more sensible to report this with NetworkManager (the second one). After all, this will not be an issue in gnome-network-displays.

i.e. an upstream report for the second issue with NetworkManager would make more sense. Please CC me if you do that as I can give more context. And please include a full backtrace if possible.

**Comment by benzea** [comment]
I believe all the bugs have already been fixed in NetworkManager upstream.

**Comment by benzea** [comment]
That also includes the issue that no name was shown for the device.

**Comment by micw** [comment]
Great news, do you know in which version or in which commit?

**Comment by benzea** [comment]
See https://gitlab.freedesktop.org/NetworkManager/NetworkManager/merge_requests/399#note_385759
