### ISSUE TITLE
Nice to have some Ubuntu build instructions

### ISSUE THREAD

**Issue by jsanta** [benzea/gnome-screencast#88]
Had to figure most of them by trial and error:
git clone git@github.com:benzea/gnome-network-displays.git
cd gnome-network-displays
sudo apt install meson appstream-util cmake libgstreamer-plugins-base1.0-dev libgstrtspserver-1.0-dev gstreamer1.0-rtsp libgtk-3-dev libnm-dev
meson build

I think I'm not missing any library.
Best regards.

**Comment by Napasso** [comment]
libpulse-dev missed in my case (ubuntu 19.10)

**Comment by vona** [comment]
libnm-dev : Depends: libnm0 (= 1.10.6-2ubuntu1.2) but 1.10.14-0ubuntu2 is to be installed
             Depends: gir1.2-nm-1.0 (= 1.10.6-2ubuntu1.2) but 1.10.14-0ubuntu2 is to be installed


cannot build on Mint 19....

**Comment by paultelles** [comment]
This is what worked for me on Ubuntu 19.10:
<a href="https://blog.paultelles.com/2020/03/how-to-install-gnome-network-displays.html" onclick="window.open('https://blog.paultelles.com/2020/03/how-to-install-gnome-network-displays.html', '_self');">
https://blog.paultelles.com/2020/03/how-to-install-gnome-network-displays.html


</a>

**Comment by benzea** [comment]
I don't really feel like adding any instructions to the repository. In the longer run, it'll just be shipped out of the box.

**Comment by benzea** [comment]
But still nice to have the blog to point people to :)

**Comment by vona** [comment]
Fine with me. I still had no time to try it yet. Let you know once it is
done.
