### ISSUE TITLE
Network-manager update

### ISSUE THREAD

**Issue by Stevy92** [benzea/gnome-screencast#89]
Thank you for the great project. I'm waiting a long time for a network-display support on Linux. 
I have working already some time with linux and compiled few programs, but never a complex one like the network manager. 
Currently I'm working on Linux Mint (I know, old packages...) which runs with NetworkManger 1.10.14. Does it makes sense to compile NetworkManager with all its dependencies and update it?
I'm pretty happy with Mint and don't want to put to much effort to switch to a new destro. 
Mint is based on Cinamon, which should be close to gnome, right? Should the program run also with Cinamon?
If it all makes no sense to stay at Mint, which destro do you recommend? Which one has the new NetworkManger already included?

Thanks a lot.

**Comment by benzea** [comment]
To be honest, it probably is too much of a pain to update everything that needs to be updated.

And, I doubt that Cinamon is not close enough to GNOME in the sense that it likely does not implement the screencast protocol and you will need to fall back to X11 (which e.g. does not work with multiple screens).

**Comment by Stevy92** [comment]
Hi benzea, 
thank you for your reply. 
And which distribution do you recommend or you are using?

**Comment by Stevy92** [comment]
I played with debian, which didn't worked out of the box. 
But now with Ubuntu 19.10 and now it works with my LG webOS TV. 

Thanks!

Just a hint for all other, who want to use it: 
To install H264 for me worked: 
sudo apt-get install gstreamer1.0-vaapi
