### ISSUE TITLE
Only compile from source and can we flatpak or copr?

### ISSUE THREAD

**Issue by DFF-fred** [benzea/gnome-screencast#96]
Hi!
I was going to install your copr repository until I found out it now gives a 404. I see in the changes some files added for flatpak as well but not really sure what to do about it. So as I said in title, is my only choice to compile from source or are there any other options?
Thank you.

**Comment by benzea** [comment]
On Fedora, simply install the RPM from the distribution …

**Comment by DFF-fred** [comment]
Hi!
I tried both dnf install screencast or dnf install gnome-screencast getting unable to find a match. Where do I find this rpm then, and/or what is the application name?
Thank you.

**Comment by benzea** [comment]
It is renamed to gnome-network-displays. I assume that will fix things :)

**Comment by DFF-fred** [comment]
Definitely! Thank you very much.
