### ISSUE TITLE
Doubled repository?

### ISSUE THREAD

**Issue by iadegesso** [benzea/gnome-screencast#97]
Which is the most updated between this and https://gitlab.gnome.org/bberg/gnome-network-displays ?

Thanks

Iade

**Comment by benzea** [comment]
It is a dated snapshot currently. Considered moving, but don't really want to move it twice …

The big advantage of the GNOME gitlab would be the ability to build flatpaks.

**Comment by iadegesso** [comment]
> It is a dated snapshot currently.

Do you mean this snapshot on GitHub?

Iade

**Comment by benzea** [comment]
No, the one on gitlab. See also #94
