### ISSUE TITLE
Change output resolution

### ISSUE THREAD

**Issue by MoonDragon-MD** [benzea/gnome-screencast#99]
How can I change output resolution?
From the terminal I receive that it cannot determine the screen resolution and starts in high resolution. This slows down the display on the TV very much.
Is there a file where I can set the output resolution?

**Comment by benzea** [comment]
If you mean the latency, I doubt it is related to the output resolution.

You cannot change the resolution currently. In fact, it currently is even hardcoded to FullHD rather than using the information discovered from the sink.

**Comment by MoonDragon-MD** [comment]
Thank you for your answer. 
At the moment I tried it on a tablet with little power, I think that's the problem.
Anyway, it would be nice to change the values!
Thank you for your work, much appreciated

**Comment by benzea** [comment]
Right, you should probably try to install gstreamer-vaapi (or whatever it is called in your distribution). This encoder should be accelerated using the graphics card, which could improve performance considerably.

As for resolution choosing; what you are describing is quite a corner case unfortunately. That said, we really should be using the resolution that the local screen has whenever it is available on the sink side. And it should be really simple to fix this; I think hardcoding it to FullHD was mostly to rule out errors at the time.

**Comment by MoonDragon-MD** [comment]
Hi, I tried to install
gstreamer1.0-vaapi intel-media-va-driver-non-free i965-va-driver-shaders
In addition, I have updated other packages in ubuntu 19.10
Now I can't even connect to the TV.
these are the logs:
1) ~$ NETWORK_DISPLAYS_H264_ENC=openh264enc G_MESSAGES_DEBUG=all gnome-network-displays
(gnome-network-displays:4731): GLib-GIO-DEBUG: 22:51:37.128: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
(gnome-network-displays:4731): Gtk-DEBUG: 22:51:37.205: Connecting to session manager
** (gnome-network-displays:4731): DEBUG: 22:51:37.400: NdScreencastPortal: Aquired Portal proxy
** (gnome-network-displays:4731): DEBUG: 22:51:37.401: task is: 0x5574a8f92ca0
** (gnome-network-displays:4731): DEBUG: 22:51:37.404: WFDP2PRegistry: Found a new device, creating provider
** (gnome-network-displays:4731): DEBUG: 22:51:37.404: WfdP2PProvider: Discover is now set to 1

** (gnome-network-displays:4731): WARNING **: 22:51:37.414: Error calling DBus method during Screencast portal initialization: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop

** (gnome-network-displays:4731): WARNING **: 22:51:37.414: Error initing screencast portal: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop

** (gnome-network-displays:4731): WARNING **: 22:51:37.414: Screencasting portal is unavailable! It is required to select the monitor to stream!

** (gnome-network-displays:4731): WARNING **: 22:51:37.414: Falling back to X11! You need to fix your setup to avoid issues (XDG Portals and/or mutter screencasting support)!
** (gnome-network-displays:4731): DEBUG: 22:51:37.423: WFDP2PRegistry: Got NMClient
** (gnome-network-displays:4731): DEBUG: 22:51:37.430: NdPulseaudio: Querying sink info by name
** (gnome-network-displays:4731): DEBUG: 22:51:37.430: NdPulseaudio: Error querying sink info
** (gnome-network-displays:4731): DEBUG: 22:51:37.430: NdPulseaudio: Got a sink info for the expected name
** (gnome-network-displays:4731): DEBUG: 22:51:42.905: WFDP2PProvider: Found a new sink with peer 0x5574a90b6b10 on device 0x5574a919e200
** (gnome-network-displays:4731): DEBUG: 22:51:42.906: SinkList: Adding a sink
** (gnome-network-displays:4731): DEBUG: 22:51:49.008: Found x264enc for video encoding.
** (gnome-network-displays:4731): DEBUG: 22:51:49.008: Found vaapih264enc for video encoding.
** (gnome-network-displays:4731): DEBUG: 22:51:49.008: Found avenc_aac for audio encoding.
** (gnome-network-displays:4731): DEBUG: 22:51:49.009: Got state change notification from streaming sink to state ND_SINK_STATE_WAIT_P2P
** (gnome-network-displays:4731): DEBUG: 22:51:49.010: WfdP2PProvider: Discover is now set to 0
** (gnome-network-displays:4731): DEBUG: 22:51:49.078: NdWfdP2PSink: Got P2P connection
** (gnome-network-displays:4731): DEBUG: 22:51:49.079: Found x264enc for video encoding.
** (gnome-network-displays:4731): DEBUG: 22:51:49.079: Found vaapih264enc for video encoding.
** (gnome-network-displays:4731): DEBUG: 22:51:49.079: Found avenc_aac for audio encoding.
** (gnome-network-displays:4731): DEBUG: 22:51:49.080: Got state change notification from streaming sink to state ND_SINK_STATE_WAIT_SOCKET
** (gnome-network-displays:4731): DEBUG: 22:52:18.248: WfdServer: Finalize
** (gnome-network-displays:4731): DEBUG: 22:52:18.248: WfdMediaFactory: Finalize
** (gnome-network-displays:4731): DEBUG: 22:52:18.248: Got state change notification from streaming sink to state ND_SINK_STATE_ERROR
** (gnome-network-displays:4731): DEBUG: 22:52:23.098: MetaSink: No usable sink is left, object has become invalid.


2) ~$ sudo lshw -c video
  *-display                 
       description: VGA compatible controller
       product: Intel Corporation
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 03
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:132 memory:a0000000-a0ffffff memory:90000000-9fffffff ioport:f000(size=64) memory:c0000-dffff


Can you suggest anything else to try?
Thanks
